2024-10-06 21:02:28,716 INFO    StreamThr :7364 [internal.py:wandb_internal():85] W&B internal server running at pid: 7364, started at: 2024-10-06 21:02:28.716047
2024-10-06 21:02:28,717 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: status
2024-10-06 21:02:28,718 INFO    WriterThread:7364 [datastore.py:open_for_write():87] open: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_210228-rzlxys8t/run-rzlxys8t.wandb
2024-10-06 21:02:28,719 DEBUG   SenderThread:7364 [sender.py:send():379] send: header
2024-10-06 21:02:28,719 DEBUG   SenderThread:7364 [sender.py:send():379] send: run
2024-10-06 21:02:28,911 INFO    SenderThread:7364 [dir_watcher.py:__init__():211] watching files in: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_210228-rzlxys8t/files
2024-10-06 21:02:28,912 INFO    SenderThread:7364 [sender.py:_start_run_threads():1188] run started: rzlxys8t with start time 1728266548.716549
2024-10-06 21:02:28,917 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: check_version
2024-10-06 21:02:28,917 DEBUG   SenderThread:7364 [sender.py:send_request():406] send_request: check_version
2024-10-06 21:02:28,977 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: run_start
2024-10-06 21:02:28,987 DEBUG   HandlerThread:7364 [system_info.py:__init__():26] System info init
2024-10-06 21:02:28,987 DEBUG   HandlerThread:7364 [system_info.py:__init__():41] System info init done
2024-10-06 21:02:28,987 INFO    HandlerThread:7364 [system_monitor.py:start():194] Starting system monitor
2024-10-06 21:02:28,987 INFO    SystemMonitor:7364 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-10-06 21:02:28,987 INFO    HandlerThread:7364 [system_monitor.py:probe():214] Collecting system info
2024-10-06 21:02:28,987 INFO    SystemMonitor:7364 [interfaces.py:start():188] Started cpu monitoring
2024-10-06 21:02:28,988 INFO    SystemMonitor:7364 [interfaces.py:start():188] Started disk monitoring
2024-10-06 21:02:28,991 INFO    SystemMonitor:7364 [interfaces.py:start():188] Started gpuapple monitoring
2024-10-06 21:02:28,993 INFO    SystemMonitor:7364 [interfaces.py:start():188] Started memory monitoring
2024-10-06 21:02:28,994 ERROR   gpuapple  :7364 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:02:28,995 INFO    SystemMonitor:7364 [interfaces.py:start():188] Started network monitoring
2024-10-06 21:02:28,995 ERROR   HandlerThread:7364 [gpu_apple.py:probe():176] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 164, in probe
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:02:28,997 DEBUG   HandlerThread:7364 [system_info.py:probe():152] Probing system
2024-10-06 21:02:28,999 DEBUG   HandlerThread:7364 [gitlib.py:_init_repo():56] git repository is invalid
2024-10-06 21:02:29,000 DEBUG   HandlerThread:7364 [system_info.py:probe():200] Probing system done
2024-10-06 21:02:29,000 DEBUG   HandlerThread:7364 [system_monitor.py:probe():223] {'os': 'macOS-14.6.1-arm64-arm-64bit', 'python': '3.12.2', 'heartbeatAt': '2024-10-07T02:02:28.997918', 'startedAt': '2024-10-07T02:02:28.710078', 'docker': None, 'cuda': None, 'args': ('data.pkl',), 'state': 'running', 'program': '/Users/milind/Desktop/valence/milind_code/non_llm.py', 'codePathLocal': 'non_llm.py', 'codePath': 'non_llm.py', 'host': 'Milinds-MacBook-Pro.local', 'username': 'milind', 'executable': '/opt/anaconda3/bin/python', 'cpu_count': 8, 'cpu_count_logical': 8, 'disk': {'/': {'total': 228.27386474609375, 'used': 166.33114624023438}}, 'gpuapple': {'type': 'arm', 'vendor': 'Apple'}, 'memory': {'total': 8.0}}
2024-10-06 21:02:29,000 INFO    HandlerThread:7364 [system_monitor.py:probe():224] Finished collecting system info
2024-10-06 21:02:29,000 INFO    HandlerThread:7364 [system_monitor.py:probe():227] Publishing system info
2024-10-06 21:02:29,000 DEBUG   HandlerThread:7364 [system_info.py:_save_conda():209] Saving list of conda packages installed into the current environment
2024-10-06 21:02:29,917 INFO    Thread-12 :7364 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_210228-rzlxys8t/files/conda-environment.yaml
2024-10-06 21:02:31,005 ERROR   gpuapple  :7364 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:02:31,177 DEBUG   HandlerThread:7364 [system_info.py:_save_conda():224] Saving conda packages done
2024-10-06 21:02:31,177 INFO    HandlerThread:7364 [system_monitor.py:probe():229] Finished publishing system info
2024-10-06 21:02:31,180 DEBUG   SenderThread:7364 [sender.py:send():379] send: files
2024-10-06 21:02:31,180 INFO    SenderThread:7364 [sender.py:_save_file():1454] saving file wandb-metadata.json with policy now
2024-10-06 21:02:31,475 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: python_packages
2024-10-06 21:02:31,475 DEBUG   SenderThread:7364 [sender.py:send_request():406] send_request: python_packages
2024-10-06 21:02:31,476 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:02:31,477 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: stop_status
2024-10-06 21:02:31,477 DEBUG   SenderThread:7364 [sender.py:send_request():406] send_request: stop_status
2024-10-06 21:02:31,478 INFO    wandb-upload_0:7364 [upload_job.py:push():130] Uploaded file /var/folders/jv/wvjkll0d0vl_clbchr37hpk40000gn/T/tmpq94ouw1kwandb/ihb6xb3w-wandb-metadata.json
2024-10-06 21:02:31,527 DEBUG   SenderThread:7364 [sender.py:send():379] send: telemetry
2024-10-06 21:02:31,921 INFO    Thread-12 :7364 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_210228-rzlxys8t/files/conda-environment.yaml
2024-10-06 21:02:31,922 INFO    Thread-12 :7364 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_210228-rzlxys8t/files/requirements.txt
2024-10-06 21:02:31,922 INFO    Thread-12 :7364 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_210228-rzlxys8t/files/wandb-metadata.json
2024-10-06 21:02:32,515 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:02:32,933 INFO    Thread-12 :7364 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_210228-rzlxys8t/files/output.log
2024-10-06 21:02:33,016 ERROR   gpuapple  :7364 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:02:33,490 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:02:34,494 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:02:34,549 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 21:02:34,949 INFO    Thread-12 :7364 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_210228-rzlxys8t/files/output.log
2024-10-06 21:02:35,028 ERROR   gpuapple  :7364 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:02:35,498 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:02:36,506 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:02:37,067 ERROR   gpuapple  :7364 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:02:37,506 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:02:38,513 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:02:39,083 ERROR   gpuapple  :7364 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:02:39,523 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:02:40,527 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 21:02:40,533 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:02:41,095 ERROR   gpuapple  :7364 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:02:41,543 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:02:42,565 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:02:43,139 ERROR   gpuapple  :7364 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:02:43,570 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:02:44,573 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:02:45,169 ERROR   gpuapple  :7364 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:02:45,575 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 21:02:45,575 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:02:46,289 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:02:46,290 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:02:46,291 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:02:46,291 DEBUG   SenderThread:7364 [sender.py:send():379] send: history
2024-10-06 21:02:46,291 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:02:46,291 DEBUG   SenderThread:7364 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:02:46,292 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:02:46,293 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:02:46,293 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:02:46,293 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:02:46,293 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:02:46,293 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:02:46,294 INFO    SenderThread:7364 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:02:46,294 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:02:46,294 DEBUG   SenderThread:7364 [sender.py:send():379] send: history
2024-10-06 21:02:46,295 DEBUG   SenderThread:7364 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:02:46,295 INFO    SenderThread:7364 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:02:46,295 DEBUG   SenderThread:7364 [sender.py:send():379] send: history
2024-10-06 21:02:46,295 DEBUG   SenderThread:7364 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:02:46,296 INFO    SenderThread:7364 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:02:46,296 DEBUG   SenderThread:7364 [sender.py:send():379] send: history
2024-10-06 21:02:46,296 DEBUG   SenderThread:7364 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:02:46,296 INFO    SenderThread:7364 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:02:46,296 DEBUG   SenderThread:7364 [sender.py:send():379] send: history
2024-10-06 21:02:46,296 DEBUG   SenderThread:7364 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:02:46,296 INFO    SenderThread:7364 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:02:46,296 DEBUG   SenderThread:7364 [sender.py:send():379] send: history
2024-10-06 21:02:46,296 DEBUG   SenderThread:7364 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:02:46,297 INFO    SenderThread:7364 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:02:46,297 DEBUG   SenderThread:7364 [sender.py:send():379] send: history
2024-10-06 21:02:46,297 DEBUG   SenderThread:7364 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:02:46,297 INFO    SenderThread:7364 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:02:46,297 DEBUG   SenderThread:7364 [sender.py:send():379] send: history
2024-10-06 21:02:46,297 DEBUG   SenderThread:7364 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:02:46,297 INFO    SenderThread:7364 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:02:46,297 DEBUG   SenderThread:7364 [sender.py:send():379] send: history
2024-10-06 21:02:46,297 DEBUG   SenderThread:7364 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:02:46,297 INFO    SenderThread:7364 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:02:46,297 DEBUG   SenderThread:7364 [sender.py:send():379] send: history
2024-10-06 21:02:46,297 DEBUG   SenderThread:7364 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:02:46,297 INFO    SenderThread:7364 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:02:46,297 DEBUG   SenderThread:7364 [sender.py:send():379] send: history
2024-10-06 21:02:46,297 DEBUG   SenderThread:7364 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:02:46,298 INFO    SenderThread:7364 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:02:46,568 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: stop_status
2024-10-06 21:02:46,568 DEBUG   SenderThread:7364 [sender.py:send_request():406] send_request: stop_status
2024-10-06 21:02:46,592 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:02:47,037 DEBUG   SenderThread:7364 [sender.py:send():379] send: telemetry
2024-10-06 21:02:47,038 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: server_info
2024-10-06 21:02:47,038 DEBUG   SenderThread:7364 [sender.py:send_request():406] send_request: server_info
2024-10-06 21:02:47,049 INFO    Thread-12 :7364 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_210228-rzlxys8t/files/wandb-summary.json
2024-10-06 21:02:47,083 DEBUG   SenderThread:7364 [sender.py:send():379] send: exit
2024-10-06 21:02:47,083 INFO    SenderThread:7364 [sender.py:send_exit():586] handling exit code: 0
2024-10-06 21:02:47,084 INFO    SenderThread:7364 [sender.py:send_exit():588] handling runtime: 18
2024-10-06 21:02:47,084 INFO    SenderThread:7364 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:02:47,084 INFO    SenderThread:7364 [sender.py:send_exit():594] send defer
2024-10-06 21:02:47,084 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:02:47,084 INFO    HandlerThread:7364 [handler.py:handle_request_defer():184] handle defer: 0
2024-10-06 21:02:47,085 DEBUG   SenderThread:7364 [sender.py:send_request():406] send_request: defer
2024-10-06 21:02:47,085 INFO    SenderThread:7364 [sender.py:send_request_defer():610] handle sender defer: 0
2024-10-06 21:02:47,085 INFO    SenderThread:7364 [sender.py:transition_state():614] send defer: 1
2024-10-06 21:02:47,085 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:02:47,085 INFO    HandlerThread:7364 [handler.py:handle_request_defer():184] handle defer: 1
2024-10-06 21:02:47,085 DEBUG   SenderThread:7364 [sender.py:send_request():406] send_request: defer
2024-10-06 21:02:47,085 INFO    SenderThread:7364 [sender.py:send_request_defer():610] handle sender defer: 1
2024-10-06 21:02:47,085 INFO    SenderThread:7364 [sender.py:transition_state():614] send defer: 2
2024-10-06 21:02:47,085 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:02:47,085 INFO    HandlerThread:7364 [handler.py:handle_request_defer():184] handle defer: 2
2024-10-06 21:02:47,085 INFO    HandlerThread:7364 [system_monitor.py:finish():203] Stopping system monitor
2024-10-06 21:02:47,085 DEBUG   SystemMonitor:7364 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-10-06 21:02:47,085 DEBUG   SystemMonitor:7364 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-10-06 21:02:47,085 DEBUG   SystemMonitor:7364 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-10-06 21:02:47,085 INFO    HandlerThread:7364 [interfaces.py:finish():200] Joined cpu monitor
2024-10-06 21:02:47,085 INFO    HandlerThread:7364 [interfaces.py:finish():200] Joined disk monitor
2024-10-06 21:02:47,085 INFO    HandlerThread:7364 [interfaces.py:finish():200] Joined gpuapple monitor
2024-10-06 21:02:47,085 INFO    HandlerThread:7364 [interfaces.py:finish():200] Joined memory monitor
2024-10-06 21:02:47,085 INFO    HandlerThread:7364 [interfaces.py:finish():200] Joined network monitor
2024-10-06 21:02:47,085 DEBUG   SenderThread:7364 [sender.py:send_request():406] send_request: defer
2024-10-06 21:02:47,085 INFO    SenderThread:7364 [sender.py:send_request_defer():610] handle sender defer: 2
2024-10-06 21:02:47,085 INFO    SenderThread:7364 [sender.py:transition_state():614] send defer: 3
2024-10-06 21:02:47,085 DEBUG   SenderThread:7364 [sender.py:send():379] send: telemetry
2024-10-06 21:02:47,085 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:02:47,085 INFO    HandlerThread:7364 [handler.py:handle_request_defer():184] handle defer: 3
2024-10-06 21:02:47,085 DEBUG   SenderThread:7364 [sender.py:send_request():406] send_request: defer
2024-10-06 21:02:47,085 INFO    SenderThread:7364 [sender.py:send_request_defer():610] handle sender defer: 3
2024-10-06 21:02:47,085 INFO    SenderThread:7364 [sender.py:transition_state():614] send defer: 4
2024-10-06 21:02:47,086 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:02:47,086 INFO    HandlerThread:7364 [handler.py:handle_request_defer():184] handle defer: 4
2024-10-06 21:02:47,086 DEBUG   SenderThread:7364 [sender.py:send_request():406] send_request: defer
2024-10-06 21:02:47,086 INFO    SenderThread:7364 [sender.py:send_request_defer():610] handle sender defer: 4
2024-10-06 21:02:47,086 INFO    SenderThread:7364 [sender.py:transition_state():614] send defer: 5
2024-10-06 21:02:47,086 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:02:47,086 INFO    HandlerThread:7364 [handler.py:handle_request_defer():184] handle defer: 5
2024-10-06 21:02:47,086 DEBUG   SenderThread:7364 [sender.py:send():379] send: summary
2024-10-06 21:02:47,086 INFO    SenderThread:7364 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:02:47,086 DEBUG   SenderThread:7364 [sender.py:send_request():406] send_request: defer
2024-10-06 21:02:47,086 INFO    SenderThread:7364 [sender.py:send_request_defer():610] handle sender defer: 5
2024-10-06 21:02:47,086 INFO    SenderThread:7364 [sender.py:transition_state():614] send defer: 6
2024-10-06 21:02:47,086 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:02:47,086 INFO    HandlerThread:7364 [handler.py:handle_request_defer():184] handle defer: 6
2024-10-06 21:02:47,086 DEBUG   SenderThread:7364 [sender.py:send_request():406] send_request: defer
2024-10-06 21:02:47,086 INFO    SenderThread:7364 [sender.py:send_request_defer():610] handle sender defer: 6
2024-10-06 21:02:47,088 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 21:02:47,161 INFO    SenderThread:7364 [sender.py:transition_state():614] send defer: 7
2024-10-06 21:02:47,161 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:02:47,161 INFO    HandlerThread:7364 [handler.py:handle_request_defer():184] handle defer: 7
2024-10-06 21:02:47,161 DEBUG   SenderThread:7364 [sender.py:send_request():406] send_request: defer
2024-10-06 21:02:47,161 INFO    SenderThread:7364 [sender.py:send_request_defer():610] handle sender defer: 7
2024-10-06 21:02:48,055 INFO    Thread-12 :7364 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_210228-rzlxys8t/files/output.log
2024-10-06 21:02:48,056 INFO    Thread-12 :7364 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_210228-rzlxys8t/files/wandb-summary.json
2024-10-06 21:02:48,056 INFO    Thread-12 :7364 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_210228-rzlxys8t/files/config.yaml
2024-10-06 21:02:48,089 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: poll_exit
2024-10-06 21:02:49,059 INFO    Thread-12 :7364 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_210228-rzlxys8t/files/output.log
2024-10-06 21:02:50,031 INFO    SenderThread:7364 [sender.py:transition_state():614] send defer: 8
2024-10-06 21:02:50,032 DEBUG   SenderThread:7364 [sender.py:send_request():406] send_request: poll_exit
2024-10-06 21:02:50,032 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:02:50,033 INFO    HandlerThread:7364 [handler.py:handle_request_defer():184] handle defer: 8
2024-10-06 21:02:50,033 DEBUG   SenderThread:7364 [sender.py:send_request():406] send_request: defer
2024-10-06 21:02:50,033 INFO    SenderThread:7364 [sender.py:send_request_defer():610] handle sender defer: 8
2024-10-06 21:02:50,033 INFO    SenderThread:7364 [job_builder.py:build():440] Attempting to build job artifact
2024-10-06 21:02:50,035 INFO    SenderThread:7364 [job_builder.py:_get_source_type():580] no source found
2024-10-06 21:02:50,035 INFO    SenderThread:7364 [sender.py:transition_state():614] send defer: 9
2024-10-06 21:02:50,035 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:02:50,035 INFO    HandlerThread:7364 [handler.py:handle_request_defer():184] handle defer: 9
2024-10-06 21:02:50,035 DEBUG   SenderThread:7364 [sender.py:send_request():406] send_request: defer
2024-10-06 21:02:50,035 INFO    SenderThread:7364 [sender.py:send_request_defer():610] handle sender defer: 9
2024-10-06 21:02:50,035 INFO    SenderThread:7364 [dir_watcher.py:finish():358] shutting down directory watcher
2024-10-06 21:02:50,065 INFO    Thread-12 :7364 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_210228-rzlxys8t/files/output.log
2024-10-06 21:02:50,066 INFO    SenderThread:7364 [dir_watcher.py:finish():388] scan: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_210228-rzlxys8t/files
2024-10-06 21:02:50,067 INFO    SenderThread:7364 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_210228-rzlxys8t/files/requirements.txt requirements.txt
2024-10-06 21:02:50,067 INFO    SenderThread:7364 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_210228-rzlxys8t/files/output.log output.log
2024-10-06 21:02:50,071 INFO    SenderThread:7364 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_210228-rzlxys8t/files/config.yaml config.yaml
2024-10-06 21:02:50,073 INFO    SenderThread:7364 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_210228-rzlxys8t/files/wandb-summary.json wandb-summary.json
2024-10-06 21:02:50,074 INFO    SenderThread:7364 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_210228-rzlxys8t/files/conda-environment.yaml conda-environment.yaml
2024-10-06 21:02:50,077 INFO    SenderThread:7364 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_210228-rzlxys8t/files/wandb-metadata.json wandb-metadata.json
2024-10-06 21:02:50,077 INFO    SenderThread:7364 [sender.py:transition_state():614] send defer: 10
2024-10-06 21:02:50,079 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:02:50,079 INFO    HandlerThread:7364 [handler.py:handle_request_defer():184] handle defer: 10
2024-10-06 21:02:50,080 DEBUG   SenderThread:7364 [sender.py:send_request():406] send_request: defer
2024-10-06 21:02:50,080 INFO    SenderThread:7364 [sender.py:send_request_defer():610] handle sender defer: 10
2024-10-06 21:02:50,080 INFO    SenderThread:7364 [file_pusher.py:finish():169] shutting down file pusher
2024-10-06 21:02:50,097 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: poll_exit
2024-10-06 21:02:50,097 DEBUG   SenderThread:7364 [sender.py:send_request():406] send_request: poll_exit
2024-10-06 21:02:50,289 INFO    wandb-upload_0:7364 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_210228-rzlxys8t/files/requirements.txt
2024-10-06 21:02:50,332 INFO    wandb-upload_1:7364 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_210228-rzlxys8t/files/output.log
2024-10-06 21:02:50,357 INFO    wandb-upload_2:7364 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_210228-rzlxys8t/files/config.yaml
2024-10-06 21:02:50,357 INFO    wandb-upload_3:7364 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_210228-rzlxys8t/files/wandb-summary.json
2024-10-06 21:02:50,421 INFO    wandb-upload_4:7364 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_210228-rzlxys8t/files/conda-environment.yaml
2024-10-06 21:02:50,626 INFO    Thread-11 (_thread_body):7364 [sender.py:transition_state():614] send defer: 11
2024-10-06 21:02:50,627 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:02:50,628 INFO    HandlerThread:7364 [handler.py:handle_request_defer():184] handle defer: 11
2024-10-06 21:02:50,628 DEBUG   SenderThread:7364 [sender.py:send_request():406] send_request: defer
2024-10-06 21:02:50,628 INFO    SenderThread:7364 [sender.py:send_request_defer():610] handle sender defer: 11
2024-10-06 21:02:50,628 INFO    SenderThread:7364 [file_pusher.py:join():175] waiting for file pusher
2024-10-06 21:02:50,631 INFO    SenderThread:7364 [sender.py:transition_state():614] send defer: 12
2024-10-06 21:02:50,631 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:02:50,631 INFO    HandlerThread:7364 [handler.py:handle_request_defer():184] handle defer: 12
2024-10-06 21:02:50,631 DEBUG   SenderThread:7364 [sender.py:send_request():406] send_request: defer
2024-10-06 21:02:50,631 INFO    SenderThread:7364 [sender.py:send_request_defer():610] handle sender defer: 12
2024-10-06 21:02:50,631 INFO    SenderThread:7364 [file_stream.py:finish():601] file stream finish called
2024-10-06 21:02:51,100 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: poll_exit
2024-10-06 21:02:52,296 INFO    SenderThread:7364 [file_stream.py:finish():605] file stream finish is done
2024-10-06 21:02:52,297 INFO    SenderThread:7364 [sender.py:transition_state():614] send defer: 13
2024-10-06 21:02:52,297 DEBUG   SenderThread:7364 [sender.py:send_request():406] send_request: poll_exit
2024-10-06 21:02:52,297 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:02:52,298 INFO    HandlerThread:7364 [handler.py:handle_request_defer():184] handle defer: 13
2024-10-06 21:02:52,298 DEBUG   SenderThread:7364 [sender.py:send_request():406] send_request: defer
2024-10-06 21:02:52,298 INFO    SenderThread:7364 [sender.py:send_request_defer():610] handle sender defer: 13
2024-10-06 21:02:52,298 INFO    SenderThread:7364 [sender.py:transition_state():614] send defer: 14
2024-10-06 21:02:52,299 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:02:52,299 DEBUG   SenderThread:7364 [sender.py:send():379] send: final
2024-10-06 21:02:52,299 INFO    HandlerThread:7364 [handler.py:handle_request_defer():184] handle defer: 14
2024-10-06 21:02:52,299 DEBUG   SenderThread:7364 [sender.py:send():379] send: footer
2024-10-06 21:02:52,299 DEBUG   SenderThread:7364 [sender.py:send_request():406] send_request: defer
2024-10-06 21:02:52,299 INFO    SenderThread:7364 [sender.py:send_request_defer():610] handle sender defer: 14
2024-10-06 21:02:52,300 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: poll_exit
2024-10-06 21:02:52,301 DEBUG   SenderThread:7364 [sender.py:send_request():406] send_request: poll_exit
2024-10-06 21:02:52,301 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:02:52,302 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: get_summary
2024-10-06 21:02:52,302 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: sampled_history
2024-10-06 21:02:52,306 DEBUG   HandlerThread:7364 [handler.py:handle_request():158] handle_request: shutdown
2024-10-06 21:02:52,306 INFO    HandlerThread:7364 [handler.py:finish():882] shutting down handler
2024-10-06 21:02:53,304 INFO    WriterThread:7364 [datastore.py:close():296] close: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_210228-rzlxys8t/run-rzlxys8t.wandb
2024-10-06 21:02:53,304 INFO    SenderThread:7364 [sender.py:finish():1608] shutting down sender
2024-10-06 21:02:53,305 INFO    SenderThread:7364 [file_pusher.py:finish():169] shutting down file pusher
2024-10-06 21:02:53,305 INFO    SenderThread:7364 [file_pusher.py:join():175] waiting for file pusher
