2024-10-06 21:26:02,963 INFO    StreamThr :8118 [internal.py:wandb_internal():85] W&B internal server running at pid: 8118, started at: 2024-10-06 21:26:02.963207
2024-10-06 21:26:02,964 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: status
2024-10-06 21:26:02,966 INFO    WriterThread:8118 [datastore.py:open_for_write():87] open: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212602-3vq9og8c/run-3vq9og8c.wandb
2024-10-06 21:26:02,966 DEBUG   SenderThread:8118 [sender.py:send():379] send: header
2024-10-06 21:26:02,966 DEBUG   SenderThread:8118 [sender.py:send():379] send: run
2024-10-06 21:26:03,259 INFO    SenderThread:8118 [dir_watcher.py:__init__():211] watching files in: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212602-3vq9og8c/files
2024-10-06 21:26:03,259 INFO    SenderThread:8118 [sender.py:_start_run_threads():1188] run started: 3vq9og8c with start time 1728267962.963826
2024-10-06 21:26:03,269 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: check_version
2024-10-06 21:26:03,269 DEBUG   SenderThread:8118 [sender.py:send_request():406] send_request: check_version
2024-10-06 21:26:03,325 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: run_start
2024-10-06 21:26:03,332 DEBUG   HandlerThread:8118 [system_info.py:__init__():26] System info init
2024-10-06 21:26:03,332 DEBUG   HandlerThread:8118 [system_info.py:__init__():41] System info init done
2024-10-06 21:26:03,332 INFO    HandlerThread:8118 [system_monitor.py:start():194] Starting system monitor
2024-10-06 21:26:03,332 INFO    SystemMonitor:8118 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-10-06 21:26:03,332 INFO    HandlerThread:8118 [system_monitor.py:probe():214] Collecting system info
2024-10-06 21:26:03,333 INFO    SystemMonitor:8118 [interfaces.py:start():188] Started cpu monitoring
2024-10-06 21:26:03,334 INFO    SystemMonitor:8118 [interfaces.py:start():188] Started disk monitoring
2024-10-06 21:26:03,337 INFO    SystemMonitor:8118 [interfaces.py:start():188] Started gpuapple monitoring
2024-10-06 21:26:03,342 ERROR   HandlerThread:8118 [gpu_apple.py:probe():176] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 164, in probe
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:26:03,343 ERROR   gpuapple  :8118 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:26:03,344 INFO    SystemMonitor:8118 [interfaces.py:start():188] Started memory monitoring
2024-10-06 21:26:03,346 DEBUG   HandlerThread:8118 [system_info.py:probe():152] Probing system
2024-10-06 21:26:03,347 INFO    SystemMonitor:8118 [interfaces.py:start():188] Started network monitoring
2024-10-06 21:26:03,349 DEBUG   HandlerThread:8118 [gitlib.py:_init_repo():56] git repository is invalid
2024-10-06 21:26:03,350 DEBUG   HandlerThread:8118 [system_info.py:probe():200] Probing system done
2024-10-06 21:26:03,350 DEBUG   HandlerThread:8118 [system_monitor.py:probe():223] {'os': 'macOS-14.6.1-arm64-arm-64bit', 'python': '3.12.2', 'heartbeatAt': '2024-10-07T02:26:03.347372', 'startedAt': '2024-10-07T02:26:02.958433', 'docker': None, 'cuda': None, 'args': ('data.pkl',), 'state': 'running', 'program': '/Users/milind/Desktop/valence/milind_code/non_llm.py', 'codePathLocal': 'non_llm.py', 'codePath': 'non_llm.py', 'host': 'Milinds-MacBook-Pro.local', 'username': 'milind', 'executable': '/opt/anaconda3/bin/python', 'cpu_count': 8, 'cpu_count_logical': 8, 'disk': {'/': {'total': 228.27386474609375, 'used': 166.44244384765625}}, 'gpuapple': {'type': 'arm', 'vendor': 'Apple'}, 'memory': {'total': 8.0}}
2024-10-06 21:26:03,350 INFO    HandlerThread:8118 [system_monitor.py:probe():224] Finished collecting system info
2024-10-06 21:26:03,350 INFO    HandlerThread:8118 [system_monitor.py:probe():227] Publishing system info
2024-10-06 21:26:03,350 DEBUG   HandlerThread:8118 [system_info.py:_save_conda():209] Saving list of conda packages installed into the current environment
2024-10-06 21:26:04,265 INFO    Thread-12 :8118 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212602-3vq9og8c/files/conda-environment.yaml
2024-10-06 21:26:05,351 ERROR   gpuapple  :8118 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:26:05,402 DEBUG   HandlerThread:8118 [system_info.py:_save_conda():224] Saving conda packages done
2024-10-06 21:26:05,403 INFO    HandlerThread:8118 [system_monitor.py:probe():229] Finished publishing system info
2024-10-06 21:26:05,405 DEBUG   SenderThread:8118 [sender.py:send():379] send: files
2024-10-06 21:26:05,405 INFO    SenderThread:8118 [sender.py:_save_file():1454] saving file wandb-metadata.json with policy now
2024-10-06 21:26:05,611 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: python_packages
2024-10-06 21:26:05,611 DEBUG   SenderThread:8118 [sender.py:send_request():406] send_request: python_packages
2024-10-06 21:26:05,612 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: stop_status
2024-10-06 21:26:05,612 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:26:05,612 DEBUG   SenderThread:8118 [sender.py:send_request():406] send_request: stop_status
2024-10-06 21:26:05,625 INFO    wandb-upload_0:8118 [upload_job.py:push():130] Uploaded file /var/folders/jv/wvjkll0d0vl_clbchr37hpk40000gn/T/tmp0komtsoowandb/10cz4paz-wandb-metadata.json
2024-10-06 21:26:05,700 DEBUG   SenderThread:8118 [sender.py:send():379] send: telemetry
2024-10-06 21:26:06,271 INFO    Thread-12 :8118 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212602-3vq9og8c/files/conda-environment.yaml
2024-10-06 21:26:06,272 INFO    Thread-12 :8118 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212602-3vq9og8c/files/output.log
2024-10-06 21:26:06,272 INFO    Thread-12 :8118 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212602-3vq9og8c/files/requirements.txt
2024-10-06 21:26:06,272 INFO    Thread-12 :8118 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212602-3vq9og8c/files/wandb-metadata.json
2024-10-06 21:26:06,617 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:26:07,362 ERROR   gpuapple  :8118 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:26:07,622 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:26:08,218 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 21:26:08,279 INFO    Thread-12 :8118 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212602-3vq9og8c/files/output.log
2024-10-06 21:26:08,644 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:26:09,370 ERROR   gpuapple  :8118 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:26:09,638 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:26:10,643 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:26:11,380 ERROR   gpuapple  :8118 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:26:11,642 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:26:12,644 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:26:13,386 ERROR   gpuapple  :8118 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:26:13,645 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:26:14,102 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 21:26:14,209 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:26:14,209 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:26:14,210 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:26:14,210 DEBUG   SenderThread:8118 [sender.py:send():379] send: history
2024-10-06 21:26:14,210 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:26:14,210 DEBUG   SenderThread:8118 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:26:14,211 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:26:14,211 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:26:14,211 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:26:14,211 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:26:14,211 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:26:14,211 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:26:14,212 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:26:14,212 INFO    SenderThread:8118 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:26:14,213 DEBUG   SenderThread:8118 [sender.py:send():379] send: history
2024-10-06 21:26:14,213 DEBUG   SenderThread:8118 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:26:14,213 INFO    SenderThread:8118 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:26:14,213 DEBUG   SenderThread:8118 [sender.py:send():379] send: history
2024-10-06 21:26:14,213 DEBUG   SenderThread:8118 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:26:14,213 INFO    SenderThread:8118 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:26:14,213 DEBUG   SenderThread:8118 [sender.py:send():379] send: history
2024-10-06 21:26:14,213 DEBUG   SenderThread:8118 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:26:14,213 INFO    SenderThread:8118 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:26:14,213 DEBUG   SenderThread:8118 [sender.py:send():379] send: history
2024-10-06 21:26:14,214 DEBUG   SenderThread:8118 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:26:14,214 INFO    SenderThread:8118 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:26:14,214 DEBUG   SenderThread:8118 [sender.py:send():379] send: history
2024-10-06 21:26:14,214 DEBUG   SenderThread:8118 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:26:14,214 INFO    SenderThread:8118 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:26:14,214 DEBUG   SenderThread:8118 [sender.py:send():379] send: history
2024-10-06 21:26:14,214 DEBUG   SenderThread:8118 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:26:14,214 INFO    SenderThread:8118 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:26:14,214 DEBUG   SenderThread:8118 [sender.py:send():379] send: history
2024-10-06 21:26:14,214 DEBUG   SenderThread:8118 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:26:14,214 INFO    SenderThread:8118 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:26:14,214 DEBUG   SenderThread:8118 [sender.py:send():379] send: history
2024-10-06 21:26:14,214 DEBUG   SenderThread:8118 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:26:14,214 INFO    SenderThread:8118 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:26:14,214 DEBUG   SenderThread:8118 [sender.py:send():379] send: history
2024-10-06 21:26:14,214 DEBUG   SenderThread:8118 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:26:14,214 INFO    SenderThread:8118 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:26:14,215 DEBUG   SenderThread:8118 [sender.py:send():379] send: history
2024-10-06 21:26:14,215 DEBUG   SenderThread:8118 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:26:14,215 INFO    SenderThread:8118 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:26:14,306 INFO    Thread-12 :8118 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212602-3vq9og8c/files/wandb-summary.json
2024-10-06 21:26:14,648 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:26:15,311 INFO    Thread-12 :8118 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212602-3vq9og8c/files/output.log
2024-10-06 21:26:15,394 ERROR   gpuapple  :8118 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:26:15,685 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:26:15,851 DEBUG   SenderThread:8118 [sender.py:send():379] send: telemetry
2024-10-06 21:26:15,853 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: server_info
2024-10-06 21:26:15,853 DEBUG   SenderThread:8118 [sender.py:send_request():406] send_request: server_info
2024-10-06 21:26:15,894 DEBUG   SenderThread:8118 [sender.py:send():379] send: exit
2024-10-06 21:26:15,894 INFO    SenderThread:8118 [sender.py:send_exit():586] handling exit code: 0
2024-10-06 21:26:15,894 INFO    SenderThread:8118 [sender.py:send_exit():588] handling runtime: 12
2024-10-06 21:26:15,894 INFO    SenderThread:8118 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:26:15,895 INFO    SenderThread:8118 [sender.py:send_exit():594] send defer
2024-10-06 21:26:15,895 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:26:15,895 INFO    HandlerThread:8118 [handler.py:handle_request_defer():184] handle defer: 0
2024-10-06 21:26:15,895 DEBUG   SenderThread:8118 [sender.py:send_request():406] send_request: defer
2024-10-06 21:26:15,895 INFO    SenderThread:8118 [sender.py:send_request_defer():610] handle sender defer: 0
2024-10-06 21:26:15,895 INFO    SenderThread:8118 [sender.py:transition_state():614] send defer: 1
2024-10-06 21:26:15,895 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:26:15,895 INFO    HandlerThread:8118 [handler.py:handle_request_defer():184] handle defer: 1
2024-10-06 21:26:15,895 DEBUG   SenderThread:8118 [sender.py:send_request():406] send_request: defer
2024-10-06 21:26:15,895 INFO    SenderThread:8118 [sender.py:send_request_defer():610] handle sender defer: 1
2024-10-06 21:26:15,895 INFO    SenderThread:8118 [sender.py:transition_state():614] send defer: 2
2024-10-06 21:26:15,895 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:26:15,895 INFO    HandlerThread:8118 [handler.py:handle_request_defer():184] handle defer: 2
2024-10-06 21:26:15,895 INFO    HandlerThread:8118 [system_monitor.py:finish():203] Stopping system monitor
2024-10-06 21:26:15,895 DEBUG   SystemMonitor:8118 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-10-06 21:26:15,895 DEBUG   SystemMonitor:8118 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-10-06 21:26:15,895 DEBUG   SystemMonitor:8118 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-10-06 21:26:15,895 INFO    HandlerThread:8118 [interfaces.py:finish():200] Joined cpu monitor
2024-10-06 21:26:15,895 INFO    HandlerThread:8118 [interfaces.py:finish():200] Joined disk monitor
2024-10-06 21:26:15,895 INFO    HandlerThread:8118 [interfaces.py:finish():200] Joined gpuapple monitor
2024-10-06 21:26:15,895 INFO    HandlerThread:8118 [interfaces.py:finish():200] Joined memory monitor
2024-10-06 21:26:15,895 INFO    HandlerThread:8118 [interfaces.py:finish():200] Joined network monitor
2024-10-06 21:26:15,896 DEBUG   SenderThread:8118 [sender.py:send_request():406] send_request: defer
2024-10-06 21:26:15,896 INFO    SenderThread:8118 [sender.py:send_request_defer():610] handle sender defer: 2
2024-10-06 21:26:15,896 INFO    SenderThread:8118 [sender.py:transition_state():614] send defer: 3
2024-10-06 21:26:15,896 DEBUG   SenderThread:8118 [sender.py:send():379] send: telemetry
2024-10-06 21:26:15,896 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:26:15,896 INFO    HandlerThread:8118 [handler.py:handle_request_defer():184] handle defer: 3
2024-10-06 21:26:15,896 DEBUG   SenderThread:8118 [sender.py:send_request():406] send_request: defer
2024-10-06 21:26:15,896 INFO    SenderThread:8118 [sender.py:send_request_defer():610] handle sender defer: 3
2024-10-06 21:26:15,896 INFO    SenderThread:8118 [sender.py:transition_state():614] send defer: 4
2024-10-06 21:26:15,896 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:26:15,896 INFO    HandlerThread:8118 [handler.py:handle_request_defer():184] handle defer: 4
2024-10-06 21:26:15,896 DEBUG   SenderThread:8118 [sender.py:send_request():406] send_request: defer
2024-10-06 21:26:15,896 INFO    SenderThread:8118 [sender.py:send_request_defer():610] handle sender defer: 4
2024-10-06 21:26:15,896 INFO    SenderThread:8118 [sender.py:transition_state():614] send defer: 5
2024-10-06 21:26:15,896 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:26:15,896 INFO    HandlerThread:8118 [handler.py:handle_request_defer():184] handle defer: 5
2024-10-06 21:26:15,896 DEBUG   SenderThread:8118 [sender.py:send():379] send: summary
2024-10-06 21:26:15,896 INFO    SenderThread:8118 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:26:15,896 DEBUG   SenderThread:8118 [sender.py:send_request():406] send_request: defer
2024-10-06 21:26:15,896 INFO    SenderThread:8118 [sender.py:send_request_defer():610] handle sender defer: 5
2024-10-06 21:26:15,896 INFO    SenderThread:8118 [sender.py:transition_state():614] send defer: 6
2024-10-06 21:26:15,896 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:26:15,896 INFO    HandlerThread:8118 [handler.py:handle_request_defer():184] handle defer: 6
2024-10-06 21:26:15,896 DEBUG   SenderThread:8118 [sender.py:send_request():406] send_request: defer
2024-10-06 21:26:15,896 INFO    SenderThread:8118 [sender.py:send_request_defer():610] handle sender defer: 6
2024-10-06 21:26:15,898 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 21:26:15,981 INFO    SenderThread:8118 [sender.py:transition_state():614] send defer: 7
2024-10-06 21:26:15,981 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:26:15,981 INFO    HandlerThread:8118 [handler.py:handle_request_defer():184] handle defer: 7
2024-10-06 21:26:15,981 DEBUG   SenderThread:8118 [sender.py:send_request():406] send_request: defer
2024-10-06 21:26:15,981 INFO    SenderThread:8118 [sender.py:send_request_defer():610] handle sender defer: 7
2024-10-06 21:26:16,317 INFO    Thread-12 :8118 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212602-3vq9og8c/files/output.log
2024-10-06 21:26:16,318 INFO    Thread-12 :8118 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212602-3vq9og8c/files/config.yaml
2024-10-06 21:26:16,318 INFO    Thread-12 :8118 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212602-3vq9og8c/files/wandb-summary.json
2024-10-06 21:26:16,899 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: poll_exit
2024-10-06 21:26:18,328 INFO    Thread-12 :8118 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212602-3vq9og8c/files/output.log
2024-10-06 21:26:19,112 INFO    SenderThread:8118 [sender.py:transition_state():614] send defer: 8
2024-10-06 21:26:19,113 DEBUG   SenderThread:8118 [sender.py:send_request():406] send_request: poll_exit
2024-10-06 21:26:19,113 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:26:19,114 INFO    HandlerThread:8118 [handler.py:handle_request_defer():184] handle defer: 8
2024-10-06 21:26:19,115 DEBUG   SenderThread:8118 [sender.py:send_request():406] send_request: defer
2024-10-06 21:26:19,115 INFO    SenderThread:8118 [sender.py:send_request_defer():610] handle sender defer: 8
2024-10-06 21:26:19,115 INFO    SenderThread:8118 [job_builder.py:build():440] Attempting to build job artifact
2024-10-06 21:26:19,116 INFO    SenderThread:8118 [job_builder.py:_get_source_type():580] no source found
2024-10-06 21:26:19,117 INFO    SenderThread:8118 [sender.py:transition_state():614] send defer: 9
2024-10-06 21:26:19,117 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:26:19,117 INFO    HandlerThread:8118 [handler.py:handle_request_defer():184] handle defer: 9
2024-10-06 21:26:19,117 DEBUG   SenderThread:8118 [sender.py:send_request():406] send_request: defer
2024-10-06 21:26:19,117 INFO    SenderThread:8118 [sender.py:send_request_defer():610] handle sender defer: 9
2024-10-06 21:26:19,117 INFO    SenderThread:8118 [dir_watcher.py:finish():358] shutting down directory watcher
2024-10-06 21:26:19,331 INFO    SenderThread:8118 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212602-3vq9og8c/files/output.log
2024-10-06 21:26:19,332 INFO    SenderThread:8118 [dir_watcher.py:finish():388] scan: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212602-3vq9og8c/files
2024-10-06 21:26:19,333 INFO    SenderThread:8118 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212602-3vq9og8c/files/requirements.txt requirements.txt
2024-10-06 21:26:19,333 INFO    SenderThread:8118 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212602-3vq9og8c/files/output.log output.log
2024-10-06 21:26:19,335 INFO    SenderThread:8118 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212602-3vq9og8c/files/config.yaml config.yaml
2024-10-06 21:26:19,337 INFO    SenderThread:8118 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212602-3vq9og8c/files/wandb-summary.json wandb-summary.json
2024-10-06 21:26:19,339 INFO    SenderThread:8118 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212602-3vq9og8c/files/conda-environment.yaml conda-environment.yaml
2024-10-06 21:26:19,341 INFO    SenderThread:8118 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212602-3vq9og8c/files/wandb-metadata.json wandb-metadata.json
2024-10-06 21:26:19,341 INFO    SenderThread:8118 [sender.py:transition_state():614] send defer: 10
2024-10-06 21:26:19,342 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:26:19,342 INFO    HandlerThread:8118 [handler.py:handle_request_defer():184] handle defer: 10
2024-10-06 21:26:19,344 DEBUG   SenderThread:8118 [sender.py:send_request():406] send_request: defer
2024-10-06 21:26:19,344 INFO    SenderThread:8118 [sender.py:send_request_defer():610] handle sender defer: 10
2024-10-06 21:26:19,344 INFO    SenderThread:8118 [file_pusher.py:finish():169] shutting down file pusher
2024-10-06 21:26:19,493 INFO    wandb-upload_0:8118 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212602-3vq9og8c/files/requirements.txt
2024-10-06 21:26:19,563 INFO    wandb-upload_1:8118 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212602-3vq9og8c/files/output.log
2024-10-06 21:26:19,612 INFO    wandb-upload_3:8118 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212602-3vq9og8c/files/wandb-summary.json
2024-10-06 21:26:19,612 INFO    wandb-upload_2:8118 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212602-3vq9og8c/files/config.yaml
2024-10-06 21:26:19,625 INFO    wandb-upload_4:8118 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212602-3vq9og8c/files/conda-environment.yaml
2024-10-06 21:26:19,830 INFO    Thread-11 (_thread_body):8118 [sender.py:transition_state():614] send defer: 11
2024-10-06 21:26:19,831 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:26:19,831 INFO    HandlerThread:8118 [handler.py:handle_request_defer():184] handle defer: 11
2024-10-06 21:26:19,832 DEBUG   SenderThread:8118 [sender.py:send_request():406] send_request: defer
2024-10-06 21:26:19,832 INFO    SenderThread:8118 [sender.py:send_request_defer():610] handle sender defer: 11
2024-10-06 21:26:19,832 INFO    SenderThread:8118 [file_pusher.py:join():175] waiting for file pusher
2024-10-06 21:26:19,834 INFO    SenderThread:8118 [sender.py:transition_state():614] send defer: 12
2024-10-06 21:26:19,834 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:26:19,834 INFO    HandlerThread:8118 [handler.py:handle_request_defer():184] handle defer: 12
2024-10-06 21:26:19,834 DEBUG   SenderThread:8118 [sender.py:send_request():406] send_request: defer
2024-10-06 21:26:19,834 INFO    SenderThread:8118 [sender.py:send_request_defer():610] handle sender defer: 12
2024-10-06 21:26:19,834 INFO    SenderThread:8118 [file_stream.py:finish():601] file stream finish called
2024-10-06 21:26:19,908 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: poll_exit
2024-10-06 21:26:19,914 INFO    SenderThread:8118 [file_stream.py:finish():605] file stream finish is done
2024-10-06 21:26:19,914 INFO    SenderThread:8118 [sender.py:transition_state():614] send defer: 13
2024-10-06 21:26:19,914 DEBUG   SenderThread:8118 [sender.py:send_request():406] send_request: poll_exit
2024-10-06 21:26:19,915 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:26:19,915 INFO    HandlerThread:8118 [handler.py:handle_request_defer():184] handle defer: 13
2024-10-06 21:26:19,916 DEBUG   SenderThread:8118 [sender.py:send_request():406] send_request: defer
2024-10-06 21:26:19,916 INFO    SenderThread:8118 [sender.py:send_request_defer():610] handle sender defer: 13
2024-10-06 21:26:19,916 INFO    SenderThread:8118 [sender.py:transition_state():614] send defer: 14
2024-10-06 21:26:19,917 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:26:19,917 INFO    HandlerThread:8118 [handler.py:handle_request_defer():184] handle defer: 14
2024-10-06 21:26:19,917 DEBUG   SenderThread:8118 [sender.py:send():379] send: final
2024-10-06 21:26:19,917 DEBUG   SenderThread:8118 [sender.py:send():379] send: footer
2024-10-06 21:26:19,918 DEBUG   SenderThread:8118 [sender.py:send_request():406] send_request: defer
2024-10-06 21:26:19,918 INFO    SenderThread:8118 [sender.py:send_request_defer():610] handle sender defer: 14
2024-10-06 21:26:19,920 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: poll_exit
2024-10-06 21:26:19,920 DEBUG   SenderThread:8118 [sender.py:send_request():406] send_request: poll_exit
2024-10-06 21:26:19,921 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:26:19,922 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: get_summary
2024-10-06 21:26:19,922 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: sampled_history
2024-10-06 21:26:19,923 DEBUG   HandlerThread:8118 [handler.py:handle_request():158] handle_request: shutdown
2024-10-06 21:26:19,924 INFO    HandlerThread:8118 [handler.py:finish():882] shutting down handler
2024-10-06 21:26:20,925 INFO    WriterThread:8118 [datastore.py:close():296] close: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212602-3vq9og8c/run-3vq9og8c.wandb
2024-10-06 21:26:20,926 INFO    SenderThread:8118 [sender.py:finish():1608] shutting down sender
2024-10-06 21:26:20,926 INFO    SenderThread:8118 [file_pusher.py:finish():169] shutting down file pusher
2024-10-06 21:26:20,926 INFO    SenderThread:8118 [file_pusher.py:join():175] waiting for file pusher
