2024-10-06 21:25:34,486 INFO    StreamThr :8042 [internal.py:wandb_internal():85] W&B internal server running at pid: 8042, started at: 2024-10-06 21:25:34.486137
2024-10-06 21:25:34,487 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: status
2024-10-06 21:25:34,488 INFO    WriterThread:8042 [datastore.py:open_for_write():87] open: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212534-7v4yd7x7/run-7v4yd7x7.wandb
2024-10-06 21:25:34,490 DEBUG   SenderThread:8042 [sender.py:send():379] send: header
2024-10-06 21:25:34,490 DEBUG   SenderThread:8042 [sender.py:send():379] send: run
2024-10-06 21:25:34,722 INFO    SenderThread:8042 [dir_watcher.py:__init__():211] watching files in: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212534-7v4yd7x7/files
2024-10-06 21:25:34,722 INFO    SenderThread:8042 [sender.py:_start_run_threads():1188] run started: 7v4yd7x7 with start time 1728267934.48678
2024-10-06 21:25:34,727 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: check_version
2024-10-06 21:25:34,728 DEBUG   SenderThread:8042 [sender.py:send_request():406] send_request: check_version
2024-10-06 21:25:34,805 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: run_start
2024-10-06 21:25:34,809 DEBUG   HandlerThread:8042 [system_info.py:__init__():26] System info init
2024-10-06 21:25:34,810 DEBUG   HandlerThread:8042 [system_info.py:__init__():41] System info init done
2024-10-06 21:25:34,810 INFO    HandlerThread:8042 [system_monitor.py:start():194] Starting system monitor
2024-10-06 21:25:34,810 INFO    SystemMonitor:8042 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-10-06 21:25:34,810 INFO    HandlerThread:8042 [system_monitor.py:probe():214] Collecting system info
2024-10-06 21:25:34,810 INFO    SystemMonitor:8042 [interfaces.py:start():188] Started cpu monitoring
2024-10-06 21:25:34,811 INFO    SystemMonitor:8042 [interfaces.py:start():188] Started disk monitoring
2024-10-06 21:25:34,813 ERROR   HandlerThread:8042 [gpu_apple.py:probe():176] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 164, in probe
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:25:34,813 INFO    SystemMonitor:8042 [interfaces.py:start():188] Started gpuapple monitoring
2024-10-06 21:25:34,814 ERROR   gpuapple  :8042 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:25:34,815 DEBUG   HandlerThread:8042 [system_info.py:probe():152] Probing system
2024-10-06 21:25:34,816 INFO    SystemMonitor:8042 [interfaces.py:start():188] Started memory monitoring
2024-10-06 21:25:34,816 INFO    SystemMonitor:8042 [interfaces.py:start():188] Started network monitoring
2024-10-06 21:25:34,818 DEBUG   HandlerThread:8042 [gitlib.py:_init_repo():56] git repository is invalid
2024-10-06 21:25:34,818 DEBUG   HandlerThread:8042 [system_info.py:probe():200] Probing system done
2024-10-06 21:25:34,818 DEBUG   HandlerThread:8042 [system_monitor.py:probe():223] {'os': 'macOS-14.6.1-arm64-arm-64bit', 'python': '3.12.2', 'heartbeatAt': '2024-10-07T02:25:34.816516', 'startedAt': '2024-10-07T02:25:34.480862', 'docker': None, 'cuda': None, 'args': ('data.pkl',), 'state': 'running', 'program': '/Users/milind/Desktop/valence/milind_code/non_llm.py', 'codePathLocal': 'non_llm.py', 'codePath': 'non_llm.py', 'host': 'Milinds-MacBook-Pro.local', 'username': 'milind', 'executable': '/opt/anaconda3/bin/python', 'cpu_count': 8, 'cpu_count_logical': 8, 'disk': {'/': {'total': 228.27386474609375, 'used': 166.43939208984375}}, 'gpuapple': {'type': 'arm', 'vendor': 'Apple'}, 'memory': {'total': 8.0}}
2024-10-06 21:25:34,818 INFO    HandlerThread:8042 [system_monitor.py:probe():224] Finished collecting system info
2024-10-06 21:25:34,818 INFO    HandlerThread:8042 [system_monitor.py:probe():227] Publishing system info
2024-10-06 21:25:34,818 DEBUG   HandlerThread:8042 [system_info.py:_save_conda():209] Saving list of conda packages installed into the current environment
2024-10-06 21:25:35,729 INFO    Thread-12 :8042 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212534-7v4yd7x7/files/conda-environment.yaml
2024-10-06 21:25:36,823 ERROR   gpuapple  :8042 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:25:36,854 DEBUG   HandlerThread:8042 [system_info.py:_save_conda():224] Saving conda packages done
2024-10-06 21:25:36,854 INFO    HandlerThread:8042 [system_monitor.py:probe():229] Finished publishing system info
2024-10-06 21:25:36,856 DEBUG   SenderThread:8042 [sender.py:send():379] send: files
2024-10-06 21:25:36,856 INFO    SenderThread:8042 [sender.py:_save_file():1454] saving file wandb-metadata.json with policy now
2024-10-06 21:25:37,076 INFO    wandb-upload_0:8042 [upload_job.py:push():130] Uploaded file /var/folders/jv/wvjkll0d0vl_clbchr37hpk40000gn/T/tmph7z8yw1pwandb/qzyjac6u-wandb-metadata.json
2024-10-06 21:25:37,091 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: python_packages
2024-10-06 21:25:37,091 DEBUG   SenderThread:8042 [sender.py:send_request():406] send_request: python_packages
2024-10-06 21:25:37,091 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: stop_status
2024-10-06 21:25:37,092 DEBUG   SenderThread:8042 [sender.py:send_request():406] send_request: stop_status
2024-10-06 21:25:37,092 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:25:37,152 DEBUG   SenderThread:8042 [sender.py:send():379] send: telemetry
2024-10-06 21:25:37,730 INFO    Thread-12 :8042 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212534-7v4yd7x7/files/conda-environment.yaml
2024-10-06 21:25:37,730 INFO    Thread-12 :8042 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212534-7v4yd7x7/files/requirements.txt
2024-10-06 21:25:37,730 INFO    Thread-12 :8042 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212534-7v4yd7x7/files/output.log
2024-10-06 21:25:37,731 INFO    Thread-12 :8042 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212534-7v4yd7x7/files/wandb-metadata.json
2024-10-06 21:25:38,122 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:25:38,830 ERROR   gpuapple  :8042 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:25:39,134 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:25:39,736 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 21:25:39,741 INFO    Thread-12 :8042 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212534-7v4yd7x7/files/output.log
2024-10-06 21:25:40,130 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:25:40,848 ERROR   gpuapple  :8042 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:25:41,159 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:25:42,135 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:25:42,857 ERROR   gpuapple  :8042 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:25:43,140 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:25:44,143 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:25:44,868 ERROR   gpuapple  :8042 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:25:45,114 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 21:25:45,144 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:25:46,147 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:25:46,873 ERROR   gpuapple  :8042 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:25:47,081 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:25:47,082 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:25:47,082 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:25:47,082 DEBUG   SenderThread:8042 [sender.py:send():379] send: history
2024-10-06 21:25:47,083 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:25:47,083 DEBUG   SenderThread:8042 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:25:47,084 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:25:47,084 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:25:47,084 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:25:47,084 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:25:47,084 INFO    SenderThread:8042 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:25:47,085 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:25:47,085 DEBUG   SenderThread:8042 [sender.py:send():379] send: history
2024-10-06 21:25:47,085 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:25:47,086 DEBUG   SenderThread:8042 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:25:47,086 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:25:47,087 INFO    SenderThread:8042 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:25:47,087 DEBUG   SenderThread:8042 [sender.py:send():379] send: history
2024-10-06 21:25:47,087 DEBUG   SenderThread:8042 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:25:47,087 INFO    SenderThread:8042 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:25:47,087 DEBUG   SenderThread:8042 [sender.py:send():379] send: history
2024-10-06 21:25:47,087 DEBUG   SenderThread:8042 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:25:47,087 INFO    SenderThread:8042 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:25:47,087 DEBUG   SenderThread:8042 [sender.py:send():379] send: history
2024-10-06 21:25:47,087 DEBUG   SenderThread:8042 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:25:47,087 INFO    SenderThread:8042 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:25:47,087 DEBUG   SenderThread:8042 [sender.py:send():379] send: history
2024-10-06 21:25:47,087 DEBUG   SenderThread:8042 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:25:47,087 INFO    SenderThread:8042 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:25:47,088 DEBUG   SenderThread:8042 [sender.py:send():379] send: history
2024-10-06 21:25:47,088 DEBUG   SenderThread:8042 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:25:47,088 INFO    SenderThread:8042 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:25:47,088 DEBUG   SenderThread:8042 [sender.py:send():379] send: history
2024-10-06 21:25:47,088 DEBUG   SenderThread:8042 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:25:47,088 INFO    SenderThread:8042 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:25:47,088 DEBUG   SenderThread:8042 [sender.py:send():379] send: history
2024-10-06 21:25:47,088 DEBUG   SenderThread:8042 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:25:47,088 INFO    SenderThread:8042 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:25:47,088 DEBUG   SenderThread:8042 [sender.py:send():379] send: history
2024-10-06 21:25:47,088 DEBUG   SenderThread:8042 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:25:47,088 INFO    SenderThread:8042 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:25:47,089 DEBUG   SenderThread:8042 [sender.py:send():379] send: history
2024-10-06 21:25:47,089 DEBUG   SenderThread:8042 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:25:47,089 INFO    SenderThread:8042 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:25:47,147 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:25:47,775 INFO    Thread-12 :8042 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212534-7v4yd7x7/files/output.log
2024-10-06 21:25:47,776 INFO    Thread-12 :8042 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212534-7v4yd7x7/files/wandb-summary.json
2024-10-06 21:25:47,974 DEBUG   SenderThread:8042 [sender.py:send():379] send: telemetry
2024-10-06 21:25:47,975 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: server_info
2024-10-06 21:25:47,975 DEBUG   SenderThread:8042 [sender.py:send_request():406] send_request: server_info
2024-10-06 21:25:48,015 DEBUG   SenderThread:8042 [sender.py:send():379] send: exit
2024-10-06 21:25:48,016 INFO    SenderThread:8042 [sender.py:send_exit():586] handling exit code: 0
2024-10-06 21:25:48,016 INFO    SenderThread:8042 [sender.py:send_exit():588] handling runtime: 13
2024-10-06 21:25:48,016 INFO    SenderThread:8042 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:25:48,016 INFO    SenderThread:8042 [sender.py:send_exit():594] send defer
2024-10-06 21:25:48,016 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:25:48,016 INFO    HandlerThread:8042 [handler.py:handle_request_defer():184] handle defer: 0
2024-10-06 21:25:48,016 DEBUG   SenderThread:8042 [sender.py:send_request():406] send_request: defer
2024-10-06 21:25:48,016 INFO    SenderThread:8042 [sender.py:send_request_defer():610] handle sender defer: 0
2024-10-06 21:25:48,016 INFO    SenderThread:8042 [sender.py:transition_state():614] send defer: 1
2024-10-06 21:25:48,016 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:25:48,016 INFO    HandlerThread:8042 [handler.py:handle_request_defer():184] handle defer: 1
2024-10-06 21:25:48,016 DEBUG   SenderThread:8042 [sender.py:send_request():406] send_request: defer
2024-10-06 21:25:48,016 INFO    SenderThread:8042 [sender.py:send_request_defer():610] handle sender defer: 1
2024-10-06 21:25:48,016 INFO    SenderThread:8042 [sender.py:transition_state():614] send defer: 2
2024-10-06 21:25:48,017 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:25:48,017 INFO    HandlerThread:8042 [handler.py:handle_request_defer():184] handle defer: 2
2024-10-06 21:25:48,017 INFO    HandlerThread:8042 [system_monitor.py:finish():203] Stopping system monitor
2024-10-06 21:25:48,017 INFO    HandlerThread:8042 [interfaces.py:finish():200] Joined cpu monitor
2024-10-06 21:25:48,017 INFO    HandlerThread:8042 [interfaces.py:finish():200] Joined disk monitor
2024-10-06 21:25:48,017 INFO    HandlerThread:8042 [interfaces.py:finish():200] Joined gpuapple monitor
2024-10-06 21:25:48,017 INFO    HandlerThread:8042 [interfaces.py:finish():200] Joined memory monitor
2024-10-06 21:25:48,017 DEBUG   SystemMonitor:8042 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-10-06 21:25:48,017 DEBUG   SystemMonitor:8042 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-10-06 21:25:48,017 DEBUG   SystemMonitor:8042 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-10-06 21:25:48,017 INFO    HandlerThread:8042 [interfaces.py:finish():200] Joined network monitor
2024-10-06 21:25:48,018 DEBUG   SenderThread:8042 [sender.py:send_request():406] send_request: defer
2024-10-06 21:25:48,018 INFO    SenderThread:8042 [sender.py:send_request_defer():610] handle sender defer: 2
2024-10-06 21:25:48,018 INFO    SenderThread:8042 [sender.py:transition_state():614] send defer: 3
2024-10-06 21:25:48,018 DEBUG   SenderThread:8042 [sender.py:send():379] send: telemetry
2024-10-06 21:25:48,018 DEBUG   SenderThread:8042 [sender.py:send():379] send: stats
2024-10-06 21:25:48,018 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:25:48,018 INFO    HandlerThread:8042 [handler.py:handle_request_defer():184] handle defer: 3
2024-10-06 21:25:48,018 DEBUG   SenderThread:8042 [sender.py:send_request():406] send_request: defer
2024-10-06 21:25:48,018 INFO    SenderThread:8042 [sender.py:send_request_defer():610] handle sender defer: 3
2024-10-06 21:25:48,018 INFO    SenderThread:8042 [sender.py:transition_state():614] send defer: 4
2024-10-06 21:25:48,018 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:25:48,018 INFO    HandlerThread:8042 [handler.py:handle_request_defer():184] handle defer: 4
2024-10-06 21:25:48,018 DEBUG   SenderThread:8042 [sender.py:send_request():406] send_request: defer
2024-10-06 21:25:48,018 INFO    SenderThread:8042 [sender.py:send_request_defer():610] handle sender defer: 4
2024-10-06 21:25:48,018 INFO    SenderThread:8042 [sender.py:transition_state():614] send defer: 5
2024-10-06 21:25:48,018 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:25:48,018 INFO    HandlerThread:8042 [handler.py:handle_request_defer():184] handle defer: 5
2024-10-06 21:25:48,018 DEBUG   SenderThread:8042 [sender.py:send():379] send: summary
2024-10-06 21:25:48,018 INFO    SenderThread:8042 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:25:48,018 DEBUG   SenderThread:8042 [sender.py:send_request():406] send_request: defer
2024-10-06 21:25:48,018 INFO    SenderThread:8042 [sender.py:send_request_defer():610] handle sender defer: 5
2024-10-06 21:25:48,018 INFO    SenderThread:8042 [sender.py:transition_state():614] send defer: 6
2024-10-06 21:25:48,018 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:25:48,018 INFO    HandlerThread:8042 [handler.py:handle_request_defer():184] handle defer: 6
2024-10-06 21:25:48,019 DEBUG   SenderThread:8042 [sender.py:send_request():406] send_request: defer
2024-10-06 21:25:48,019 INFO    SenderThread:8042 [sender.py:send_request_defer():610] handle sender defer: 6
2024-10-06 21:25:48,020 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 21:25:48,097 INFO    SenderThread:8042 [sender.py:transition_state():614] send defer: 7
2024-10-06 21:25:48,097 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:25:48,097 INFO    HandlerThread:8042 [handler.py:handle_request_defer():184] handle defer: 7
2024-10-06 21:25:48,097 DEBUG   SenderThread:8042 [sender.py:send_request():406] send_request: defer
2024-10-06 21:25:48,097 INFO    SenderThread:8042 [sender.py:send_request_defer():610] handle sender defer: 7
2024-10-06 21:25:48,784 INFO    Thread-12 :8042 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212534-7v4yd7x7/files/wandb-summary.json
2024-10-06 21:25:48,784 INFO    Thread-12 :8042 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212534-7v4yd7x7/files/output.log
2024-10-06 21:25:48,784 INFO    Thread-12 :8042 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212534-7v4yd7x7/files/config.yaml
2024-10-06 21:25:49,021 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: poll_exit
2024-10-06 21:25:49,788 INFO    Thread-12 :8042 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212534-7v4yd7x7/files/output.log
2024-10-06 21:25:50,720 INFO    SenderThread:8042 [sender.py:transition_state():614] send defer: 8
2024-10-06 21:25:50,720 DEBUG   SenderThread:8042 [sender.py:send_request():406] send_request: poll_exit
2024-10-06 21:25:50,720 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:25:50,721 INFO    HandlerThread:8042 [handler.py:handle_request_defer():184] handle defer: 8
2024-10-06 21:25:50,721 DEBUG   SenderThread:8042 [sender.py:send_request():406] send_request: defer
2024-10-06 21:25:50,721 INFO    SenderThread:8042 [sender.py:send_request_defer():610] handle sender defer: 8
2024-10-06 21:25:50,721 INFO    SenderThread:8042 [job_builder.py:build():440] Attempting to build job artifact
2024-10-06 21:25:50,722 INFO    SenderThread:8042 [job_builder.py:_get_source_type():580] no source found
2024-10-06 21:25:50,722 INFO    SenderThread:8042 [sender.py:transition_state():614] send defer: 9
2024-10-06 21:25:50,723 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:25:50,723 INFO    HandlerThread:8042 [handler.py:handle_request_defer():184] handle defer: 9
2024-10-06 21:25:50,723 DEBUG   SenderThread:8042 [sender.py:send_request():406] send_request: defer
2024-10-06 21:25:50,723 INFO    SenderThread:8042 [sender.py:send_request_defer():610] handle sender defer: 9
2024-10-06 21:25:50,723 INFO    SenderThread:8042 [dir_watcher.py:finish():358] shutting down directory watcher
2024-10-06 21:25:50,794 INFO    Thread-12 :8042 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212534-7v4yd7x7/files/output.log
2024-10-06 21:25:50,795 INFO    SenderThread:8042 [dir_watcher.py:finish():388] scan: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212534-7v4yd7x7/files
2024-10-06 21:25:50,795 INFO    SenderThread:8042 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212534-7v4yd7x7/files/requirements.txt requirements.txt
2024-10-06 21:25:50,795 INFO    SenderThread:8042 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212534-7v4yd7x7/files/output.log output.log
2024-10-06 21:25:50,795 INFO    SenderThread:8042 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212534-7v4yd7x7/files/config.yaml config.yaml
2024-10-06 21:25:50,799 INFO    SenderThread:8042 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212534-7v4yd7x7/files/wandb-summary.json wandb-summary.json
2024-10-06 21:25:50,800 INFO    SenderThread:8042 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212534-7v4yd7x7/files/conda-environment.yaml conda-environment.yaml
2024-10-06 21:25:50,802 INFO    SenderThread:8042 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212534-7v4yd7x7/files/wandb-metadata.json wandb-metadata.json
2024-10-06 21:25:50,803 INFO    SenderThread:8042 [sender.py:transition_state():614] send defer: 10
2024-10-06 21:25:50,804 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:25:50,804 INFO    HandlerThread:8042 [handler.py:handle_request_defer():184] handle defer: 10
2024-10-06 21:25:50,806 DEBUG   SenderThread:8042 [sender.py:send_request():406] send_request: defer
2024-10-06 21:25:50,806 INFO    SenderThread:8042 [sender.py:send_request_defer():610] handle sender defer: 10
2024-10-06 21:25:50,807 INFO    SenderThread:8042 [file_pusher.py:finish():169] shutting down file pusher
2024-10-06 21:25:50,992 INFO    wandb-upload_0:8042 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212534-7v4yd7x7/files/requirements.txt
2024-10-06 21:25:51,026 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: poll_exit
2024-10-06 21:25:51,027 DEBUG   SenderThread:8042 [sender.py:send_request():406] send_request: poll_exit
2024-10-06 21:25:51,035 INFO    wandb-upload_1:8042 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212534-7v4yd7x7/files/output.log
2024-10-06 21:25:51,052 INFO    wandb-upload_4:8042 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212534-7v4yd7x7/files/conda-environment.yaml
2024-10-06 21:25:51,078 INFO    wandb-upload_2:8042 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212534-7v4yd7x7/files/config.yaml
2024-10-06 21:25:51,318 INFO    wandb-upload_3:8042 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212534-7v4yd7x7/files/wandb-summary.json
2024-10-06 21:25:51,524 INFO    Thread-11 (_thread_body):8042 [sender.py:transition_state():614] send defer: 11
2024-10-06 21:25:51,524 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:25:51,525 INFO    HandlerThread:8042 [handler.py:handle_request_defer():184] handle defer: 11
2024-10-06 21:25:51,525 DEBUG   SenderThread:8042 [sender.py:send_request():406] send_request: defer
2024-10-06 21:25:51,525 INFO    SenderThread:8042 [sender.py:send_request_defer():610] handle sender defer: 11
2024-10-06 21:25:51,525 INFO    SenderThread:8042 [file_pusher.py:join():175] waiting for file pusher
2024-10-06 21:25:51,527 INFO    SenderThread:8042 [sender.py:transition_state():614] send defer: 12
2024-10-06 21:25:51,527 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:25:51,528 INFO    HandlerThread:8042 [handler.py:handle_request_defer():184] handle defer: 12
2024-10-06 21:25:51,528 DEBUG   SenderThread:8042 [sender.py:send_request():406] send_request: defer
2024-10-06 21:25:51,528 INFO    SenderThread:8042 [sender.py:send_request_defer():610] handle sender defer: 12
2024-10-06 21:25:51,528 INFO    SenderThread:8042 [file_stream.py:finish():601] file stream finish called
2024-10-06 21:25:52,030 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: poll_exit
2024-10-06 21:25:52,564 INFO    SenderThread:8042 [file_stream.py:finish():605] file stream finish is done
2024-10-06 21:25:52,564 INFO    SenderThread:8042 [sender.py:transition_state():614] send defer: 13
2024-10-06 21:25:52,565 DEBUG   SenderThread:8042 [sender.py:send_request():406] send_request: poll_exit
2024-10-06 21:25:52,565 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:25:52,565 INFO    HandlerThread:8042 [handler.py:handle_request_defer():184] handle defer: 13
2024-10-06 21:25:52,565 DEBUG   SenderThread:8042 [sender.py:send_request():406] send_request: defer
2024-10-06 21:25:52,565 INFO    SenderThread:8042 [sender.py:send_request_defer():610] handle sender defer: 13
2024-10-06 21:25:52,566 INFO    SenderThread:8042 [sender.py:transition_state():614] send defer: 14
2024-10-06 21:25:52,566 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:25:52,566 DEBUG   SenderThread:8042 [sender.py:send():379] send: final
2024-10-06 21:25:52,566 INFO    HandlerThread:8042 [handler.py:handle_request_defer():184] handle defer: 14
2024-10-06 21:25:52,566 DEBUG   SenderThread:8042 [sender.py:send():379] send: footer
2024-10-06 21:25:52,566 DEBUG   SenderThread:8042 [sender.py:send_request():406] send_request: defer
2024-10-06 21:25:52,566 INFO    SenderThread:8042 [sender.py:send_request_defer():610] handle sender defer: 14
2024-10-06 21:25:52,567 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: poll_exit
2024-10-06 21:25:52,567 DEBUG   SenderThread:8042 [sender.py:send_request():406] send_request: poll_exit
2024-10-06 21:25:52,568 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:25:52,569 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: get_summary
2024-10-06 21:25:52,569 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: sampled_history
2024-10-06 21:25:52,571 DEBUG   HandlerThread:8042 [handler.py:handle_request():158] handle_request: shutdown
2024-10-06 21:25:52,571 INFO    HandlerThread:8042 [handler.py:finish():882] shutting down handler
2024-10-06 21:25:53,568 INFO    WriterThread:8042 [datastore.py:close():296] close: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212534-7v4yd7x7/run-7v4yd7x7.wandb
2024-10-06 21:25:53,572 INFO    SenderThread:8042 [sender.py:finish():1608] shutting down sender
2024-10-06 21:25:53,572 INFO    SenderThread:8042 [file_pusher.py:finish():169] shutting down file pusher
2024-10-06 21:25:53,572 INFO    SenderThread:8042 [file_pusher.py:join():175] waiting for file pusher
