2024-10-06 21:24:51,118 INFO    StreamThr :7993 [internal.py:wandb_internal():85] W&B internal server running at pid: 7993, started at: 2024-10-06 21:24:51.117452
2024-10-06 21:24:51,120 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: status
2024-10-06 21:24:51,122 INFO    WriterThread:7993 [datastore.py:open_for_write():87] open: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212451-yru066wq/run-yru066wq.wandb
2024-10-06 21:24:51,123 DEBUG   SenderThread:7993 [sender.py:send():379] send: header
2024-10-06 21:24:51,123 DEBUG   SenderThread:7993 [sender.py:send():379] send: run
2024-10-06 21:24:51,614 INFO    SenderThread:7993 [dir_watcher.py:__init__():211] watching files in: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212451-yru066wq/files
2024-10-06 21:24:51,614 INFO    SenderThread:7993 [sender.py:_start_run_threads():1188] run started: yru066wq with start time 1728267891.117998
2024-10-06 21:24:51,620 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: check_version
2024-10-06 21:24:51,620 DEBUG   SenderThread:7993 [sender.py:send_request():406] send_request: check_version
2024-10-06 21:24:52,766 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: run_start
2024-10-06 21:24:52,776 DEBUG   HandlerThread:7993 [system_info.py:__init__():26] System info init
2024-10-06 21:24:52,776 DEBUG   HandlerThread:7993 [system_info.py:__init__():41] System info init done
2024-10-06 21:24:52,776 INFO    HandlerThread:7993 [system_monitor.py:start():194] Starting system monitor
2024-10-06 21:24:52,776 INFO    SystemMonitor:7993 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-10-06 21:24:52,776 INFO    HandlerThread:7993 [system_monitor.py:probe():214] Collecting system info
2024-10-06 21:24:52,778 INFO    SystemMonitor:7993 [interfaces.py:start():188] Started cpu monitoring
2024-10-06 21:24:52,781 ERROR   HandlerThread:7993 [gpu_apple.py:probe():176] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 164, in probe
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:24:52,782 INFO    SystemMonitor:7993 [interfaces.py:start():188] Started disk monitoring
2024-10-06 21:24:52,784 DEBUG   HandlerThread:7993 [system_info.py:probe():152] Probing system
2024-10-06 21:24:52,786 INFO    SystemMonitor:7993 [interfaces.py:start():188] Started gpuapple monitoring
2024-10-06 21:24:52,787 ERROR   gpuapple  :7993 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:24:52,788 INFO    SystemMonitor:7993 [interfaces.py:start():188] Started memory monitoring
2024-10-06 21:24:52,789 INFO    SystemMonitor:7993 [interfaces.py:start():188] Started network monitoring
2024-10-06 21:24:52,791 DEBUG   HandlerThread:7993 [gitlib.py:_init_repo():56] git repository is invalid
2024-10-06 21:24:52,791 DEBUG   HandlerThread:7993 [system_info.py:probe():200] Probing system done
2024-10-06 21:24:52,791 DEBUG   HandlerThread:7993 [system_monitor.py:probe():223] {'os': 'macOS-14.6.1-arm64-arm-64bit', 'python': '3.12.2', 'heartbeatAt': '2024-10-07T02:24:52.786782', 'startedAt': '2024-10-07T02:24:51.106483', 'docker': None, 'cuda': None, 'args': ('data.pkl',), 'state': 'running', 'program': '/Users/milind/Desktop/valence/milind_code/non_llm.py', 'codePathLocal': 'non_llm.py', 'codePath': 'non_llm.py', 'host': 'Milinds-MacBook-Pro.local', 'username': 'milind', 'executable': '/opt/anaconda3/bin/python', 'cpu_count': 8, 'cpu_count_logical': 8, 'disk': {'/': {'total': 228.27386474609375, 'used': 166.43721771240234}}, 'gpuapple': {'type': 'arm', 'vendor': 'Apple'}, 'memory': {'total': 8.0}}
2024-10-06 21:24:52,791 INFO    HandlerThread:7993 [system_monitor.py:probe():224] Finished collecting system info
2024-10-06 21:24:52,791 INFO    HandlerThread:7993 [system_monitor.py:probe():227] Publishing system info
2024-10-06 21:24:52,791 DEBUG   HandlerThread:7993 [system_info.py:_save_conda():209] Saving list of conda packages installed into the current environment
2024-10-06 21:24:53,625 INFO    Thread-12 :7993 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212451-yru066wq/files/conda-environment.yaml
2024-10-06 21:24:54,796 ERROR   gpuapple  :7993 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:24:54,837 DEBUG   HandlerThread:7993 [system_info.py:_save_conda():224] Saving conda packages done
2024-10-06 21:24:54,838 INFO    HandlerThread:7993 [system_monitor.py:probe():229] Finished publishing system info
2024-10-06 21:24:54,840 DEBUG   SenderThread:7993 [sender.py:send():379] send: files
2024-10-06 21:24:54,840 INFO    SenderThread:7993 [sender.py:_save_file():1454] saving file wandb-metadata.json with policy now
2024-10-06 21:24:55,016 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: python_packages
2024-10-06 21:24:55,016 DEBUG   SenderThread:7993 [sender.py:send_request():406] send_request: python_packages
2024-10-06 21:24:55,016 DEBUG   SenderThread:7993 [sender.py:send():379] send: telemetry
2024-10-06 21:24:55,017 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: stop_status
2024-10-06 21:24:55,017 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:24:55,017 DEBUG   SenderThread:7993 [sender.py:send_request():406] send_request: stop_status
2024-10-06 21:24:55,229 INFO    wandb-upload_0:7993 [upload_job.py:push():130] Uploaded file /var/folders/jv/wvjkll0d0vl_clbchr37hpk40000gn/T/tmpzp0iyd1qwandb/sf2tei0e-wandb-metadata.json
2024-10-06 21:24:55,635 INFO    Thread-12 :7993 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212451-yru066wq/files/conda-environment.yaml
2024-10-06 21:24:55,635 INFO    Thread-12 :7993 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212451-yru066wq/files/wandb-metadata.json
2024-10-06 21:24:55,635 INFO    Thread-12 :7993 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212451-yru066wq/files/output.log
2024-10-06 21:24:55,635 INFO    Thread-12 :7993 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212451-yru066wq/files/requirements.txt
2024-10-06 21:24:56,022 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:24:56,617 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 21:24:56,803 ERROR   gpuapple  :7993 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:24:57,030 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:24:57,642 INFO    Thread-12 :7993 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212451-yru066wq/files/output.log
2024-10-06 21:24:58,035 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:24:58,813 ERROR   gpuapple  :7993 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:24:59,041 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:25:00,046 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:25:00,825 ERROR   gpuapple  :7993 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:25:01,049 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:25:02,037 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 21:25:02,053 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:25:02,840 ERROR   gpuapple  :7993 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:25:03,057 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:25:04,062 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:25:04,848 ERROR   gpuapple  :7993 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:25:04,897 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:25:04,898 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:25:04,898 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:25:04,898 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:25:04,899 DEBUG   SenderThread:7993 [sender.py:send():379] send: history
2024-10-06 21:25:04,899 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:25:04,899 DEBUG   SenderThread:7993 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:25:04,899 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:25:04,900 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:25:04,900 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:25:04,900 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:25:04,900 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:25:04,901 INFO    SenderThread:7993 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:25:04,902 DEBUG   SenderThread:7993 [sender.py:send():379] send: history
2024-10-06 21:25:04,902 DEBUG   SenderThread:7993 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:25:04,902 INFO    SenderThread:7993 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:25:04,902 DEBUG   SenderThread:7993 [sender.py:send():379] send: history
2024-10-06 21:25:04,902 DEBUG   SenderThread:7993 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:25:04,902 INFO    SenderThread:7993 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:25:04,902 DEBUG   SenderThread:7993 [sender.py:send():379] send: history
2024-10-06 21:25:04,902 DEBUG   SenderThread:7993 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:25:04,902 INFO    SenderThread:7993 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:25:04,902 DEBUG   SenderThread:7993 [sender.py:send():379] send: history
2024-10-06 21:25:04,902 DEBUG   SenderThread:7993 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:25:04,902 INFO    SenderThread:7993 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:25:04,903 DEBUG   SenderThread:7993 [sender.py:send():379] send: history
2024-10-06 21:25:04,903 DEBUG   SenderThread:7993 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:25:04,903 INFO    SenderThread:7993 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:25:04,903 DEBUG   SenderThread:7993 [sender.py:send():379] send: history
2024-10-06 21:25:04,903 DEBUG   SenderThread:7993 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:25:04,903 INFO    SenderThread:7993 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:25:04,903 DEBUG   SenderThread:7993 [sender.py:send():379] send: history
2024-10-06 21:25:04,903 DEBUG   SenderThread:7993 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:25:04,903 INFO    SenderThread:7993 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:25:04,903 DEBUG   SenderThread:7993 [sender.py:send():379] send: history
2024-10-06 21:25:04,903 DEBUG   SenderThread:7993 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:25:04,903 INFO    SenderThread:7993 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:25:04,903 DEBUG   SenderThread:7993 [sender.py:send():379] send: history
2024-10-06 21:25:04,903 DEBUG   SenderThread:7993 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:25:04,903 INFO    SenderThread:7993 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:25:05,067 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:25:05,075 DEBUG   SenderThread:7993 [sender.py:send():379] send: exit
2024-10-06 21:25:05,075 INFO    SenderThread:7993 [sender.py:send_exit():586] handling exit code: 1
2024-10-06 21:25:05,075 INFO    SenderThread:7993 [sender.py:send_exit():588] handling runtime: 12
2024-10-06 21:25:05,076 INFO    SenderThread:7993 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:25:05,076 INFO    SenderThread:7993 [sender.py:send_exit():594] send defer
2024-10-06 21:25:05,076 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:25:05,076 INFO    HandlerThread:7993 [handler.py:handle_request_defer():184] handle defer: 0
2024-10-06 21:25:05,076 DEBUG   SenderThread:7993 [sender.py:send_request():406] send_request: defer
2024-10-06 21:25:05,076 INFO    SenderThread:7993 [sender.py:send_request_defer():610] handle sender defer: 0
2024-10-06 21:25:05,076 INFO    SenderThread:7993 [sender.py:transition_state():614] send defer: 1
2024-10-06 21:25:05,076 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:25:05,076 INFO    HandlerThread:7993 [handler.py:handle_request_defer():184] handle defer: 1
2024-10-06 21:25:05,076 DEBUG   SenderThread:7993 [sender.py:send_request():406] send_request: defer
2024-10-06 21:25:05,076 INFO    SenderThread:7993 [sender.py:send_request_defer():610] handle sender defer: 1
2024-10-06 21:25:05,076 INFO    SenderThread:7993 [sender.py:transition_state():614] send defer: 2
2024-10-06 21:25:05,076 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:25:05,076 INFO    HandlerThread:7993 [handler.py:handle_request_defer():184] handle defer: 2
2024-10-06 21:25:05,076 INFO    HandlerThread:7993 [system_monitor.py:finish():203] Stopping system monitor
2024-10-06 21:25:05,076 DEBUG   SystemMonitor:7993 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-10-06 21:25:05,076 DEBUG   SystemMonitor:7993 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-10-06 21:25:05,076 DEBUG   SystemMonitor:7993 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-10-06 21:25:05,077 INFO    HandlerThread:7993 [interfaces.py:finish():200] Joined cpu monitor
2024-10-06 21:25:05,077 INFO    HandlerThread:7993 [interfaces.py:finish():200] Joined disk monitor
2024-10-06 21:25:05,077 INFO    HandlerThread:7993 [interfaces.py:finish():200] Joined gpuapple monitor
2024-10-06 21:25:05,077 INFO    HandlerThread:7993 [interfaces.py:finish():200] Joined memory monitor
2024-10-06 21:25:05,077 INFO    HandlerThread:7993 [interfaces.py:finish():200] Joined network monitor
2024-10-06 21:25:05,077 DEBUG   SenderThread:7993 [sender.py:send_request():406] send_request: defer
2024-10-06 21:25:05,077 INFO    SenderThread:7993 [sender.py:send_request_defer():610] handle sender defer: 2
2024-10-06 21:25:05,077 INFO    SenderThread:7993 [sender.py:transition_state():614] send defer: 3
2024-10-06 21:25:05,077 DEBUG   SenderThread:7993 [sender.py:send():379] send: telemetry
2024-10-06 21:25:05,077 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:25:05,077 INFO    HandlerThread:7993 [handler.py:handle_request_defer():184] handle defer: 3
2024-10-06 21:25:05,077 DEBUG   SenderThread:7993 [sender.py:send_request():406] send_request: defer
2024-10-06 21:25:05,077 INFO    SenderThread:7993 [sender.py:send_request_defer():610] handle sender defer: 3
2024-10-06 21:25:05,077 INFO    SenderThread:7993 [sender.py:transition_state():614] send defer: 4
2024-10-06 21:25:05,077 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:25:05,077 INFO    HandlerThread:7993 [handler.py:handle_request_defer():184] handle defer: 4
2024-10-06 21:25:05,077 DEBUG   SenderThread:7993 [sender.py:send_request():406] send_request: defer
2024-10-06 21:25:05,077 INFO    SenderThread:7993 [sender.py:send_request_defer():610] handle sender defer: 4
2024-10-06 21:25:05,077 INFO    SenderThread:7993 [sender.py:transition_state():614] send defer: 5
2024-10-06 21:25:05,077 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:25:05,077 INFO    HandlerThread:7993 [handler.py:handle_request_defer():184] handle defer: 5
2024-10-06 21:25:05,077 DEBUG   SenderThread:7993 [sender.py:send():379] send: summary
2024-10-06 21:25:05,078 INFO    SenderThread:7993 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:25:05,078 DEBUG   SenderThread:7993 [sender.py:send_request():406] send_request: defer
2024-10-06 21:25:05,078 INFO    SenderThread:7993 [sender.py:send_request_defer():610] handle sender defer: 5
2024-10-06 21:25:05,078 INFO    SenderThread:7993 [sender.py:transition_state():614] send defer: 6
2024-10-06 21:25:05,078 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:25:05,078 INFO    HandlerThread:7993 [handler.py:handle_request_defer():184] handle defer: 6
2024-10-06 21:25:05,078 DEBUG   SenderThread:7993 [sender.py:send_request():406] send_request: defer
2024-10-06 21:25:05,078 INFO    SenderThread:7993 [sender.py:send_request_defer():610] handle sender defer: 6
2024-10-06 21:25:05,079 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 21:25:05,153 INFO    SenderThread:7993 [sender.py:transition_state():614] send defer: 7
2024-10-06 21:25:05,153 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:25:05,153 INFO    HandlerThread:7993 [handler.py:handle_request_defer():184] handle defer: 7
2024-10-06 21:25:05,153 DEBUG   SenderThread:7993 [sender.py:send_request():406] send_request: defer
2024-10-06 21:25:05,153 INFO    SenderThread:7993 [sender.py:send_request_defer():610] handle sender defer: 7
2024-10-06 21:25:05,680 INFO    Thread-12 :7993 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212451-yru066wq/files/output.log
2024-10-06 21:25:05,681 INFO    Thread-12 :7993 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212451-yru066wq/files/config.yaml
2024-10-06 21:25:05,681 INFO    Thread-12 :7993 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212451-yru066wq/files/wandb-summary.json
2024-10-06 21:25:05,850 INFO    SenderThread:7993 [sender.py:transition_state():614] send defer: 8
2024-10-06 21:25:05,851 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:25:05,851 INFO    HandlerThread:7993 [handler.py:handle_request_defer():184] handle defer: 8
2024-10-06 21:25:05,851 DEBUG   SenderThread:7993 [sender.py:send_request():406] send_request: defer
2024-10-06 21:25:05,851 INFO    SenderThread:7993 [sender.py:send_request_defer():610] handle sender defer: 8
2024-10-06 21:25:05,851 INFO    SenderThread:7993 [job_builder.py:build():440] Attempting to build job artifact
2024-10-06 21:25:05,852 INFO    SenderThread:7993 [job_builder.py:_get_source_type():580] no source found
2024-10-06 21:25:05,852 INFO    SenderThread:7993 [sender.py:transition_state():614] send defer: 9
2024-10-06 21:25:05,852 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:25:05,852 INFO    HandlerThread:7993 [handler.py:handle_request_defer():184] handle defer: 9
2024-10-06 21:25:05,853 DEBUG   SenderThread:7993 [sender.py:send_request():406] send_request: defer
2024-10-06 21:25:05,853 INFO    SenderThread:7993 [sender.py:send_request_defer():610] handle sender defer: 9
2024-10-06 21:25:05,853 INFO    SenderThread:7993 [dir_watcher.py:finish():358] shutting down directory watcher
2024-10-06 21:25:06,081 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: poll_exit
2024-10-06 21:25:06,686 INFO    Thread-12 :7993 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212451-yru066wq/files/output.log
2024-10-06 21:25:06,687 INFO    SenderThread:7993 [dir_watcher.py:finish():388] scan: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212451-yru066wq/files
2024-10-06 21:25:06,688 INFO    SenderThread:7993 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212451-yru066wq/files/requirements.txt requirements.txt
2024-10-06 21:25:06,688 INFO    SenderThread:7993 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212451-yru066wq/files/output.log output.log
2024-10-06 21:25:06,689 INFO    SenderThread:7993 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212451-yru066wq/files/config.yaml config.yaml
2024-10-06 21:25:06,693 INFO    SenderThread:7993 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212451-yru066wq/files/wandb-summary.json wandb-summary.json
2024-10-06 21:25:06,694 INFO    SenderThread:7993 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212451-yru066wq/files/conda-environment.yaml conda-environment.yaml
2024-10-06 21:25:06,698 INFO    SenderThread:7993 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212451-yru066wq/files/wandb-metadata.json wandb-metadata.json
2024-10-06 21:25:06,698 INFO    SenderThread:7993 [sender.py:transition_state():614] send defer: 10
2024-10-06 21:25:06,698 DEBUG   SenderThread:7993 [sender.py:send_request():406] send_request: poll_exit
2024-10-06 21:25:06,699 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:25:06,701 INFO    HandlerThread:7993 [handler.py:handle_request_defer():184] handle defer: 10
2024-10-06 21:25:06,701 DEBUG   SenderThread:7993 [sender.py:send_request():406] send_request: defer
2024-10-06 21:25:06,701 INFO    SenderThread:7993 [sender.py:send_request_defer():610] handle sender defer: 10
2024-10-06 21:25:06,701 INFO    SenderThread:7993 [file_pusher.py:finish():169] shutting down file pusher
2024-10-06 21:25:06,875 INFO    wandb-upload_0:7993 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212451-yru066wq/files/requirements.txt
2024-10-06 21:25:06,935 INFO    wandb-upload_1:7993 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212451-yru066wq/files/output.log
2024-10-06 21:25:06,941 INFO    wandb-upload_3:7993 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212451-yru066wq/files/wandb-summary.json
2024-10-06 21:25:06,941 INFO    wandb-upload_2:7993 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212451-yru066wq/files/config.yaml
2024-10-06 21:25:06,942 INFO    wandb-upload_4:7993 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212451-yru066wq/files/conda-environment.yaml
2024-10-06 21:25:07,086 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: poll_exit
2024-10-06 21:25:07,086 DEBUG   SenderThread:7993 [sender.py:send_request():406] send_request: poll_exit
2024-10-06 21:25:07,148 INFO    Thread-11 (_thread_body):7993 [sender.py:transition_state():614] send defer: 11
2024-10-06 21:25:07,148 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:25:07,149 INFO    HandlerThread:7993 [handler.py:handle_request_defer():184] handle defer: 11
2024-10-06 21:25:07,149 DEBUG   SenderThread:7993 [sender.py:send_request():406] send_request: defer
2024-10-06 21:25:07,149 INFO    SenderThread:7993 [sender.py:send_request_defer():610] handle sender defer: 11
2024-10-06 21:25:07,149 INFO    SenderThread:7993 [file_pusher.py:join():175] waiting for file pusher
2024-10-06 21:25:07,150 INFO    SenderThread:7993 [sender.py:transition_state():614] send defer: 12
2024-10-06 21:25:07,151 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:25:07,151 INFO    HandlerThread:7993 [handler.py:handle_request_defer():184] handle defer: 12
2024-10-06 21:25:07,151 DEBUG   SenderThread:7993 [sender.py:send_request():406] send_request: defer
2024-10-06 21:25:07,151 INFO    SenderThread:7993 [sender.py:send_request_defer():610] handle sender defer: 12
2024-10-06 21:25:07,151 INFO    SenderThread:7993 [file_stream.py:finish():601] file stream finish called
2024-10-06 21:25:07,606 INFO    SenderThread:7993 [file_stream.py:finish():605] file stream finish is done
2024-10-06 21:25:07,607 INFO    SenderThread:7993 [sender.py:transition_state():614] send defer: 13
2024-10-06 21:25:07,607 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:25:07,607 INFO    HandlerThread:7993 [handler.py:handle_request_defer():184] handle defer: 13
2024-10-06 21:25:07,608 DEBUG   SenderThread:7993 [sender.py:send_request():406] send_request: defer
2024-10-06 21:25:07,608 INFO    SenderThread:7993 [sender.py:send_request_defer():610] handle sender defer: 13
2024-10-06 21:25:07,608 INFO    SenderThread:7993 [sender.py:transition_state():614] send defer: 14
2024-10-06 21:25:07,609 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:25:07,609 DEBUG   SenderThread:7993 [sender.py:send():379] send: final
2024-10-06 21:25:07,609 INFO    HandlerThread:7993 [handler.py:handle_request_defer():184] handle defer: 14
2024-10-06 21:25:07,609 DEBUG   SenderThread:7993 [sender.py:send():379] send: footer
2024-10-06 21:25:07,609 DEBUG   SenderThread:7993 [sender.py:send_request():406] send_request: defer
2024-10-06 21:25:07,609 INFO    SenderThread:7993 [sender.py:send_request_defer():610] handle sender defer: 14
2024-10-06 21:25:07,610 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: poll_exit
2024-10-06 21:25:07,610 DEBUG   SenderThread:7993 [sender.py:send_request():406] send_request: poll_exit
2024-10-06 21:25:07,611 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: server_info
2024-10-06 21:25:07,611 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: poll_exit
2024-10-06 21:25:07,611 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: get_summary
2024-10-06 21:25:07,612 DEBUG   SenderThread:7993 [sender.py:send_request():406] send_request: server_info
2024-10-06 21:25:07,613 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: sampled_history
2024-10-06 21:25:07,615 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:25:07,663 DEBUG   SenderThread:7993 [sender.py:send_request():406] send_request: poll_exit
2024-10-06 21:25:07,664 INFO    MainThread:7993 [wandb_run.py:_footer_history_summary_info():3991] rendering history
2024-10-06 21:25:07,664 INFO    MainThread:7993 [wandb_run.py:_footer_history_summary_info():4023] rendering summary
2024-10-06 21:25:07,664 INFO    MainThread:7993 [wandb_run.py:_footer_sync_info():3950] logging synced files
2024-10-06 21:25:07,665 DEBUG   HandlerThread:7993 [handler.py:handle_request():158] handle_request: shutdown
2024-10-06 21:25:07,665 INFO    HandlerThread:7993 [handler.py:finish():882] shutting down handler
2024-10-06 21:25:08,614 INFO    WriterThread:7993 [datastore.py:close():296] close: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212451-yru066wq/run-yru066wq.wandb
2024-10-06 21:25:08,665 INFO    SenderThread:7993 [sender.py:finish():1608] shutting down sender
2024-10-06 21:25:08,665 INFO    SenderThread:7993 [file_pusher.py:finish():169] shutting down file pusher
2024-10-06 21:25:08,666 INFO    SenderThread:7993 [file_pusher.py:join():175] waiting for file pusher
