2024-10-06 21:39:53,893 INFO    StreamThr :8605 [internal.py:wandb_internal():85] W&B internal server running at pid: 8605, started at: 2024-10-06 21:39:53.891684
2024-10-06 21:39:53,894 DEBUG   HandlerThread:8605 [handler.py:handle_request():158] handle_request: status
2024-10-06 21:39:53,894 INFO    WriterThread:8605 [datastore.py:open_for_write():87] open: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213953-lkp6hr9n/run-lkp6hr9n.wandb
2024-10-06 21:39:53,897 DEBUG   SenderThread:8605 [sender.py:send():379] send: header
2024-10-06 21:39:53,897 DEBUG   SenderThread:8605 [sender.py:send():379] send: run
2024-10-06 21:39:54,104 INFO    SenderThread:8605 [dir_watcher.py:__init__():211] watching files in: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213953-lkp6hr9n/files
2024-10-06 21:39:54,104 INFO    SenderThread:8605 [sender.py:_start_run_threads():1188] run started: lkp6hr9n with start time 1728268793.893019
2024-10-06 21:39:54,109 DEBUG   HandlerThread:8605 [handler.py:handle_request():158] handle_request: check_version
2024-10-06 21:39:54,109 DEBUG   SenderThread:8605 [sender.py:send_request():406] send_request: check_version
2024-10-06 21:39:54,173 DEBUG   HandlerThread:8605 [handler.py:handle_request():158] handle_request: run_start
2024-10-06 21:39:54,181 DEBUG   HandlerThread:8605 [system_info.py:__init__():26] System info init
2024-10-06 21:39:54,181 DEBUG   HandlerThread:8605 [system_info.py:__init__():41] System info init done
2024-10-06 21:39:54,181 INFO    HandlerThread:8605 [system_monitor.py:start():194] Starting system monitor
2024-10-06 21:39:54,181 INFO    SystemMonitor:8605 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-10-06 21:39:54,181 INFO    HandlerThread:8605 [system_monitor.py:probe():214] Collecting system info
2024-10-06 21:39:54,184 INFO    SystemMonitor:8605 [interfaces.py:start():188] Started cpu monitoring
2024-10-06 21:39:54,186 ERROR   HandlerThread:8605 [gpu_apple.py:probe():176] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 164, in probe
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:39:54,187 INFO    SystemMonitor:8605 [interfaces.py:start():188] Started disk monitoring
2024-10-06 21:39:54,189 DEBUG   HandlerThread:8605 [system_info.py:probe():152] Probing system
2024-10-06 21:39:54,189 INFO    SystemMonitor:8605 [interfaces.py:start():188] Started gpuapple monitoring
2024-10-06 21:39:54,191 INFO    SystemMonitor:8605 [interfaces.py:start():188] Started memory monitoring
2024-10-06 21:39:54,191 ERROR   gpuapple  :8605 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:39:54,193 INFO    SystemMonitor:8605 [interfaces.py:start():188] Started network monitoring
2024-10-06 21:39:54,195 DEBUG   HandlerThread:8605 [gitlib.py:_init_repo():56] git repository is invalid
2024-10-06 21:39:54,195 DEBUG   HandlerThread:8605 [system_info.py:probe():200] Probing system done
2024-10-06 21:39:54,195 DEBUG   HandlerThread:8605 [system_monitor.py:probe():223] {'os': 'macOS-14.6.1-arm64-arm-64bit', 'python': '3.12.2', 'heartbeatAt': '2024-10-07T02:39:54.189512', 'startedAt': '2024-10-07T02:39:53.885122', 'docker': None, 'cuda': None, 'args': ('data.pkl',), 'state': 'running', 'program': '/Users/milind/Desktop/valence/milind_code/non_llm.py', 'codePathLocal': 'non_llm.py', 'codePath': 'non_llm.py', 'host': 'Milinds-MacBook-Pro.local', 'username': 'milind', 'executable': '/opt/anaconda3/bin/python', 'cpu_count': 8, 'cpu_count_logical': 8, 'disk': {'/': {'total': 228.27386474609375, 'used': 166.77537155151367}}, 'gpuapple': {'type': 'arm', 'vendor': 'Apple'}, 'memory': {'total': 8.0}}
2024-10-06 21:39:54,195 INFO    HandlerThread:8605 [system_monitor.py:probe():224] Finished collecting system info
2024-10-06 21:39:54,195 INFO    HandlerThread:8605 [system_monitor.py:probe():227] Publishing system info
2024-10-06 21:39:54,195 DEBUG   HandlerThread:8605 [system_info.py:_save_conda():209] Saving list of conda packages installed into the current environment
2024-10-06 21:39:55,108 INFO    Thread-12 :8605 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213953-lkp6hr9n/files/conda-environment.yaml
2024-10-06 21:39:56,200 ERROR   gpuapple  :8605 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:39:56,241 DEBUG   HandlerThread:8605 [system_info.py:_save_conda():224] Saving conda packages done
2024-10-06 21:39:56,242 INFO    HandlerThread:8605 [system_monitor.py:probe():229] Finished publishing system info
2024-10-06 21:39:56,244 DEBUG   SenderThread:8605 [sender.py:send():379] send: files
2024-10-06 21:39:56,244 INFO    SenderThread:8605 [sender.py:_save_file():1454] saving file wandb-metadata.json with policy now
2024-10-06 21:39:56,466 INFO    wandb-upload_0:8605 [upload_job.py:push():130] Uploaded file /var/folders/jv/wvjkll0d0vl_clbchr37hpk40000gn/T/tmpee36e864wandb/l8f29srd-wandb-metadata.json
2024-10-06 21:39:56,570 DEBUG   HandlerThread:8605 [handler.py:handle_request():158] handle_request: python_packages
2024-10-06 21:39:56,570 DEBUG   SenderThread:8605 [sender.py:send_request():406] send_request: python_packages
2024-10-06 21:39:56,571 DEBUG   HandlerThread:8605 [handler.py:handle_request():158] handle_request: stop_status
2024-10-06 21:39:56,572 DEBUG   HandlerThread:8605 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:39:56,573 DEBUG   SenderThread:8605 [sender.py:send_request():406] send_request: stop_status
2024-10-06 21:39:56,638 DEBUG   SenderThread:8605 [sender.py:send():379] send: telemetry
2024-10-06 21:39:57,118 INFO    Thread-12 :8605 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213953-lkp6hr9n/files/conda-environment.yaml
2024-10-06 21:39:57,118 INFO    Thread-12 :8605 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213953-lkp6hr9n/files/requirements.txt
2024-10-06 21:39:57,118 INFO    Thread-12 :8605 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213953-lkp6hr9n/files/wandb-metadata.json
2024-10-06 21:39:57,572 DEBUG   HandlerThread:8605 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:39:58,205 ERROR   gpuapple  :8605 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:39:58,576 DEBUG   HandlerThread:8605 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:39:59,579 DEBUG   HandlerThread:8605 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:39:59,649 DEBUG   HandlerThread:8605 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 21:40:00,208 ERROR   gpuapple  :8605 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:40:00,584 DEBUG   HandlerThread:8605 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:40:01,589 DEBUG   HandlerThread:8605 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:40:02,215 ERROR   gpuapple  :8605 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:40:02,594 DEBUG   HandlerThread:8605 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:40:03,599 DEBUG   HandlerThread:8605 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:40:04,223 ERROR   gpuapple  :8605 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:40:04,657 DEBUG   HandlerThread:8605 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:40:04,684 DEBUG   HandlerThread:8605 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:40:04,686 DEBUG   SenderThread:8605 [sender.py:send():379] send: history
2024-10-06 21:40:04,686 DEBUG   HandlerThread:8605 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 21:40:04,686 DEBUG   SenderThread:8605 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:40:04,687 INFO    SenderThread:8605 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:40:04,690 DEBUG   SenderThread:8605 [sender.py:send():379] send: telemetry
2024-10-06 21:40:04,691 DEBUG   HandlerThread:8605 [handler.py:handle_request():158] handle_request: server_info
2024-10-06 21:40:04,691 DEBUG   SenderThread:8605 [sender.py:send_request():406] send_request: server_info
2024-10-06 21:40:04,725 DEBUG   SenderThread:8605 [sender.py:send():379] send: exit
2024-10-06 21:40:04,726 INFO    SenderThread:8605 [sender.py:send_exit():586] handling exit code: 0
2024-10-06 21:40:04,726 INFO    SenderThread:8605 [sender.py:send_exit():588] handling runtime: 10
2024-10-06 21:40:04,726 INFO    SenderThread:8605 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:40:04,726 INFO    SenderThread:8605 [sender.py:send_exit():594] send defer
2024-10-06 21:40:04,726 DEBUG   HandlerThread:8605 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:40:04,726 INFO    HandlerThread:8605 [handler.py:handle_request_defer():184] handle defer: 0
2024-10-06 21:40:04,726 DEBUG   SenderThread:8605 [sender.py:send_request():406] send_request: defer
2024-10-06 21:40:04,726 INFO    SenderThread:8605 [sender.py:send_request_defer():610] handle sender defer: 0
2024-10-06 21:40:04,726 INFO    SenderThread:8605 [sender.py:transition_state():614] send defer: 1
2024-10-06 21:40:04,726 DEBUG   HandlerThread:8605 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:40:04,726 INFO    HandlerThread:8605 [handler.py:handle_request_defer():184] handle defer: 1
2024-10-06 21:40:04,726 DEBUG   SenderThread:8605 [sender.py:send_request():406] send_request: defer
2024-10-06 21:40:04,726 INFO    SenderThread:8605 [sender.py:send_request_defer():610] handle sender defer: 1
2024-10-06 21:40:04,726 INFO    SenderThread:8605 [sender.py:transition_state():614] send defer: 2
2024-10-06 21:40:04,726 DEBUG   HandlerThread:8605 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:40:04,726 INFO    HandlerThread:8605 [handler.py:handle_request_defer():184] handle defer: 2
2024-10-06 21:40:04,726 INFO    HandlerThread:8605 [system_monitor.py:finish():203] Stopping system monitor
2024-10-06 21:40:04,727 DEBUG   SystemMonitor:8605 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-10-06 21:40:04,727 DEBUG   SystemMonitor:8605 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-10-06 21:40:04,727 INFO    HandlerThread:8605 [interfaces.py:finish():200] Joined cpu monitor
2024-10-06 21:40:04,727 DEBUG   SystemMonitor:8605 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-10-06 21:40:04,727 INFO    HandlerThread:8605 [interfaces.py:finish():200] Joined disk monitor
2024-10-06 21:40:04,727 INFO    HandlerThread:8605 [interfaces.py:finish():200] Joined gpuapple monitor
2024-10-06 21:40:04,727 INFO    HandlerThread:8605 [interfaces.py:finish():200] Joined memory monitor
2024-10-06 21:40:04,727 INFO    HandlerThread:8605 [interfaces.py:finish():200] Joined network monitor
2024-10-06 21:40:04,727 DEBUG   SenderThread:8605 [sender.py:send_request():406] send_request: defer
2024-10-06 21:40:04,727 INFO    SenderThread:8605 [sender.py:send_request_defer():610] handle sender defer: 2
2024-10-06 21:40:04,727 INFO    SenderThread:8605 [sender.py:transition_state():614] send defer: 3
2024-10-06 21:40:04,727 DEBUG   SenderThread:8605 [sender.py:send():379] send: telemetry
2024-10-06 21:40:04,727 DEBUG   HandlerThread:8605 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:40:04,727 DEBUG   SenderThread:8605 [sender.py:send():379] send: stats
2024-10-06 21:40:04,727 INFO    HandlerThread:8605 [handler.py:handle_request_defer():184] handle defer: 3
2024-10-06 21:40:04,728 DEBUG   SenderThread:8605 [sender.py:send_request():406] send_request: defer
2024-10-06 21:40:04,728 INFO    SenderThread:8605 [sender.py:send_request_defer():610] handle sender defer: 3
2024-10-06 21:40:04,728 INFO    SenderThread:8605 [sender.py:transition_state():614] send defer: 4
2024-10-06 21:40:04,728 DEBUG   HandlerThread:8605 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:40:04,728 INFO    HandlerThread:8605 [handler.py:handle_request_defer():184] handle defer: 4
2024-10-06 21:40:04,728 DEBUG   SenderThread:8605 [sender.py:send_request():406] send_request: defer
2024-10-06 21:40:04,728 INFO    SenderThread:8605 [sender.py:send_request_defer():610] handle sender defer: 4
2024-10-06 21:40:04,728 INFO    SenderThread:8605 [sender.py:transition_state():614] send defer: 5
2024-10-06 21:40:04,728 DEBUG   HandlerThread:8605 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:40:04,728 INFO    HandlerThread:8605 [handler.py:handle_request_defer():184] handle defer: 5
2024-10-06 21:40:04,728 DEBUG   SenderThread:8605 [sender.py:send():379] send: summary
2024-10-06 21:40:04,728 INFO    SenderThread:8605 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:40:04,728 DEBUG   SenderThread:8605 [sender.py:send_request():406] send_request: defer
2024-10-06 21:40:04,728 INFO    SenderThread:8605 [sender.py:send_request_defer():610] handle sender defer: 5
2024-10-06 21:40:04,728 INFO    SenderThread:8605 [sender.py:transition_state():614] send defer: 6
2024-10-06 21:40:04,728 DEBUG   HandlerThread:8605 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:40:04,728 INFO    HandlerThread:8605 [handler.py:handle_request_defer():184] handle defer: 6
2024-10-06 21:40:04,728 DEBUG   SenderThread:8605 [sender.py:send_request():406] send_request: defer
2024-10-06 21:40:04,728 INFO    SenderThread:8605 [sender.py:send_request_defer():610] handle sender defer: 6
2024-10-06 21:40:04,730 DEBUG   HandlerThread:8605 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 21:40:04,828 INFO    SenderThread:8605 [sender.py:transition_state():614] send defer: 7
2024-10-06 21:40:04,828 DEBUG   HandlerThread:8605 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:40:04,829 INFO    HandlerThread:8605 [handler.py:handle_request_defer():184] handle defer: 7
2024-10-06 21:40:04,829 DEBUG   SenderThread:8605 [sender.py:send_request():406] send_request: defer
2024-10-06 21:40:04,829 INFO    SenderThread:8605 [sender.py:send_request_defer():610] handle sender defer: 7
2024-10-06 21:40:05,156 INFO    Thread-12 :8605 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213953-lkp6hr9n/files/config.yaml
2024-10-06 21:40:05,157 INFO    Thread-12 :8605 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213953-lkp6hr9n/files/output.log
2024-10-06 21:40:05,157 INFO    Thread-12 :8605 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213953-lkp6hr9n/files/wandb-summary.json
2024-10-06 21:40:05,732 DEBUG   HandlerThread:8605 [handler.py:handle_request():158] handle_request: poll_exit
2024-10-06 21:40:06,694 INFO    SenderThread:8605 [sender.py:transition_state():614] send defer: 8
2024-10-06 21:40:06,698 DEBUG   SenderThread:8605 [sender.py:send_request():406] send_request: poll_exit
2024-10-06 21:40:06,698 DEBUG   HandlerThread:8605 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:40:06,699 INFO    HandlerThread:8605 [handler.py:handle_request_defer():184] handle defer: 8
2024-10-06 21:40:06,700 DEBUG   SenderThread:8605 [sender.py:send_request():406] send_request: defer
2024-10-06 21:40:06,701 INFO    SenderThread:8605 [sender.py:send_request_defer():610] handle sender defer: 8
2024-10-06 21:40:06,701 INFO    SenderThread:8605 [job_builder.py:build():440] Attempting to build job artifact
2024-10-06 21:40:06,703 INFO    SenderThread:8605 [job_builder.py:_get_source_type():580] no source found
2024-10-06 21:40:06,703 INFO    SenderThread:8605 [sender.py:transition_state():614] send defer: 9
2024-10-06 21:40:06,703 DEBUG   HandlerThread:8605 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:40:06,704 INFO    HandlerThread:8605 [handler.py:handle_request_defer():184] handle defer: 9
2024-10-06 21:40:06,705 DEBUG   SenderThread:8605 [sender.py:send_request():406] send_request: defer
2024-10-06 21:40:06,705 INFO    SenderThread:8605 [sender.py:send_request_defer():610] handle sender defer: 9
2024-10-06 21:40:06,705 INFO    SenderThread:8605 [dir_watcher.py:finish():358] shutting down directory watcher
2024-10-06 21:40:06,737 DEBUG   HandlerThread:8605 [handler.py:handle_request():158] handle_request: poll_exit
2024-10-06 21:40:07,162 INFO    Thread-12 :8605 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213953-lkp6hr9n/files/output.log
2024-10-06 21:40:07,164 INFO    SenderThread:8605 [dir_watcher.py:finish():388] scan: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213953-lkp6hr9n/files
2024-10-06 21:40:07,164 INFO    SenderThread:8605 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213953-lkp6hr9n/files/requirements.txt requirements.txt
2024-10-06 21:40:07,165 INFO    SenderThread:8605 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213953-lkp6hr9n/files/output.log output.log
2024-10-06 21:40:07,170 INFO    SenderThread:8605 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213953-lkp6hr9n/files/config.yaml config.yaml
2024-10-06 21:40:07,172 INFO    SenderThread:8605 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213953-lkp6hr9n/files/wandb-summary.json wandb-summary.json
2024-10-06 21:40:07,175 INFO    SenderThread:8605 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213953-lkp6hr9n/files/conda-environment.yaml conda-environment.yaml
2024-10-06 21:40:07,177 INFO    SenderThread:8605 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213953-lkp6hr9n/files/wandb-metadata.json wandb-metadata.json
2024-10-06 21:40:07,177 INFO    SenderThread:8605 [sender.py:transition_state():614] send defer: 10
2024-10-06 21:40:07,179 DEBUG   SenderThread:8605 [sender.py:send_request():406] send_request: poll_exit
2024-10-06 21:40:07,179 DEBUG   HandlerThread:8605 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:40:07,180 INFO    HandlerThread:8605 [handler.py:handle_request_defer():184] handle defer: 10
2024-10-06 21:40:07,180 DEBUG   SenderThread:8605 [sender.py:send_request():406] send_request: defer
2024-10-06 21:40:07,180 INFO    SenderThread:8605 [sender.py:send_request_defer():610] handle sender defer: 10
2024-10-06 21:40:07,180 INFO    SenderThread:8605 [file_pusher.py:finish():169] shutting down file pusher
2024-10-06 21:40:07,372 INFO    wandb-upload_0:8605 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213953-lkp6hr9n/files/requirements.txt
2024-10-06 21:40:07,402 INFO    wandb-upload_4:8605 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213953-lkp6hr9n/files/conda-environment.yaml
2024-10-06 21:40:07,428 INFO    wandb-upload_1:8605 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213953-lkp6hr9n/files/output.log
2024-10-06 21:40:07,430 INFO    wandb-upload_3:8605 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213953-lkp6hr9n/files/wandb-summary.json
2024-10-06 21:40:07,656 INFO    wandb-upload_2:8605 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213953-lkp6hr9n/files/config.yaml
2024-10-06 21:40:07,744 DEBUG   HandlerThread:8605 [handler.py:handle_request():158] handle_request: poll_exit
2024-10-06 21:40:07,745 DEBUG   SenderThread:8605 [sender.py:send_request():406] send_request: poll_exit
2024-10-06 21:40:07,862 INFO    Thread-11 (_thread_body):8605 [sender.py:transition_state():614] send defer: 11
2024-10-06 21:40:07,863 DEBUG   HandlerThread:8605 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:40:07,863 INFO    HandlerThread:8605 [handler.py:handle_request_defer():184] handle defer: 11
2024-10-06 21:40:07,864 DEBUG   SenderThread:8605 [sender.py:send_request():406] send_request: defer
2024-10-06 21:40:07,864 INFO    SenderThread:8605 [sender.py:send_request_defer():610] handle sender defer: 11
2024-10-06 21:40:07,864 INFO    SenderThread:8605 [file_pusher.py:join():175] waiting for file pusher
2024-10-06 21:40:07,865 INFO    SenderThread:8605 [sender.py:transition_state():614] send defer: 12
2024-10-06 21:40:07,865 DEBUG   HandlerThread:8605 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:40:07,865 INFO    HandlerThread:8605 [handler.py:handle_request_defer():184] handle defer: 12
2024-10-06 21:40:07,865 DEBUG   SenderThread:8605 [sender.py:send_request():406] send_request: defer
2024-10-06 21:40:07,865 INFO    SenderThread:8605 [sender.py:send_request_defer():610] handle sender defer: 12
2024-10-06 21:40:07,866 INFO    SenderThread:8605 [file_stream.py:finish():601] file stream finish called
2024-10-06 21:40:07,932 INFO    SenderThread:8605 [file_stream.py:finish():605] file stream finish is done
2024-10-06 21:40:07,932 INFO    SenderThread:8605 [sender.py:transition_state():614] send defer: 13
2024-10-06 21:40:07,932 DEBUG   HandlerThread:8605 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:40:07,932 INFO    HandlerThread:8605 [handler.py:handle_request_defer():184] handle defer: 13
2024-10-06 21:40:07,932 DEBUG   SenderThread:8605 [sender.py:send_request():406] send_request: defer
2024-10-06 21:40:07,932 INFO    SenderThread:8605 [sender.py:send_request_defer():610] handle sender defer: 13
2024-10-06 21:40:07,932 INFO    SenderThread:8605 [sender.py:transition_state():614] send defer: 14
2024-10-06 21:40:07,933 DEBUG   HandlerThread:8605 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:40:07,933 DEBUG   SenderThread:8605 [sender.py:send():379] send: final
2024-10-06 21:40:07,933 INFO    HandlerThread:8605 [handler.py:handle_request_defer():184] handle defer: 14
2024-10-06 21:40:07,933 DEBUG   SenderThread:8605 [sender.py:send():379] send: footer
2024-10-06 21:40:07,933 DEBUG   SenderThread:8605 [sender.py:send_request():406] send_request: defer
2024-10-06 21:40:07,933 INFO    SenderThread:8605 [sender.py:send_request_defer():610] handle sender defer: 14
2024-10-06 21:40:07,934 DEBUG   HandlerThread:8605 [handler.py:handle_request():158] handle_request: poll_exit
2024-10-06 21:40:07,934 DEBUG   SenderThread:8605 [sender.py:send_request():406] send_request: poll_exit
2024-10-06 21:40:07,935 DEBUG   HandlerThread:8605 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:40:07,936 DEBUG   HandlerThread:8605 [handler.py:handle_request():158] handle_request: get_summary
2024-10-06 21:40:07,937 DEBUG   HandlerThread:8605 [handler.py:handle_request():158] handle_request: sampled_history
2024-10-06 21:40:07,941 DEBUG   HandlerThread:8605 [handler.py:handle_request():158] handle_request: shutdown
2024-10-06 21:40:07,941 INFO    HandlerThread:8605 [handler.py:finish():882] shutting down handler
2024-10-06 21:40:08,938 INFO    WriterThread:8605 [datastore.py:close():296] close: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_213953-lkp6hr9n/run-lkp6hr9n.wandb
2024-10-06 21:40:08,938 INFO    SenderThread:8605 [sender.py:finish():1608] shutting down sender
2024-10-06 21:40:08,940 INFO    SenderThread:8605 [file_pusher.py:finish():169] shutting down file pusher
2024-10-06 21:40:08,940 INFO    SenderThread:8605 [file_pusher.py:join():175] waiting for file pusher
