2024-10-06 21:23:29,859 INFO    StreamThr :7925 [internal.py:wandb_internal():85] W&B internal server running at pid: 7925, started at: 2024-10-06 21:23:29.859034
2024-10-06 21:23:29,860 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: status
2024-10-06 21:23:29,861 INFO    WriterThread:7925 [datastore.py:open_for_write():87] open: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212329-b73j8oav/run-b73j8oav.wandb
2024-10-06 21:23:29,862 DEBUG   SenderThread:7925 [sender.py:send():379] send: header
2024-10-06 21:23:29,862 DEBUG   SenderThread:7925 [sender.py:send():379] send: run
2024-10-06 21:23:30,109 INFO    SenderThread:7925 [dir_watcher.py:__init__():211] watching files in: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212329-b73j8oav/files
2024-10-06 21:23:30,109 INFO    SenderThread:7925 [sender.py:_start_run_threads():1188] run started: b73j8oav with start time 1728267809.859431
2024-10-06 21:23:30,115 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: check_version
2024-10-06 21:23:30,115 DEBUG   SenderThread:7925 [sender.py:send_request():406] send_request: check_version
2024-10-06 21:23:30,170 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: run_start
2024-10-06 21:23:30,177 DEBUG   HandlerThread:7925 [system_info.py:__init__():26] System info init
2024-10-06 21:23:30,178 DEBUG   HandlerThread:7925 [system_info.py:__init__():41] System info init done
2024-10-06 21:23:30,178 INFO    HandlerThread:7925 [system_monitor.py:start():194] Starting system monitor
2024-10-06 21:23:30,178 INFO    SystemMonitor:7925 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-10-06 21:23:30,178 INFO    HandlerThread:7925 [system_monitor.py:probe():214] Collecting system info
2024-10-06 21:23:30,180 INFO    SystemMonitor:7925 [interfaces.py:start():188] Started cpu monitoring
2024-10-06 21:23:30,182 ERROR   HandlerThread:7925 [gpu_apple.py:probe():176] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 164, in probe
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:23:30,183 INFO    SystemMonitor:7925 [interfaces.py:start():188] Started disk monitoring
2024-10-06 21:23:30,185 DEBUG   HandlerThread:7925 [system_info.py:probe():152] Probing system
2024-10-06 21:23:30,185 INFO    SystemMonitor:7925 [interfaces.py:start():188] Started gpuapple monitoring
2024-10-06 21:23:30,187 ERROR   gpuapple  :7925 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:23:30,188 INFO    SystemMonitor:7925 [interfaces.py:start():188] Started memory monitoring
2024-10-06 21:23:30,188 INFO    SystemMonitor:7925 [interfaces.py:start():188] Started network monitoring
2024-10-06 21:23:30,190 DEBUG   HandlerThread:7925 [gitlib.py:_init_repo():56] git repository is invalid
2024-10-06 21:23:30,190 DEBUG   HandlerThread:7925 [system_info.py:probe():200] Probing system done
2024-10-06 21:23:30,190 DEBUG   HandlerThread:7925 [system_monitor.py:probe():223] {'os': 'macOS-14.6.1-arm64-arm-64bit', 'python': '3.12.2', 'heartbeatAt': '2024-10-07T02:23:30.185622', 'startedAt': '2024-10-07T02:23:29.851780', 'docker': None, 'cuda': None, 'args': ('data.pkl',), 'state': 'running', 'program': '/Users/milind/Desktop/valence/milind_code/non_llm.py', 'codePathLocal': 'non_llm.py', 'codePath': 'non_llm.py', 'host': 'Milinds-MacBook-Pro.local', 'username': 'milind', 'executable': '/opt/anaconda3/bin/python', 'cpu_count': 8, 'cpu_count_logical': 8, 'disk': {'/': {'total': 228.27386474609375, 'used': 166.43209075927734}}, 'gpuapple': {'type': 'arm', 'vendor': 'Apple'}, 'memory': {'total': 8.0}}
2024-10-06 21:23:30,190 INFO    HandlerThread:7925 [system_monitor.py:probe():224] Finished collecting system info
2024-10-06 21:23:30,190 INFO    HandlerThread:7925 [system_monitor.py:probe():227] Publishing system info
2024-10-06 21:23:30,190 DEBUG   HandlerThread:7925 [system_info.py:_save_conda():209] Saving list of conda packages installed into the current environment
2024-10-06 21:23:31,115 INFO    Thread-12 :7925 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212329-b73j8oav/files/conda-environment.yaml
2024-10-06 21:23:32,195 ERROR   gpuapple  :7925 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:23:32,392 DEBUG   HandlerThread:7925 [system_info.py:_save_conda():224] Saving conda packages done
2024-10-06 21:23:32,393 INFO    HandlerThread:7925 [system_monitor.py:probe():229] Finished publishing system info
2024-10-06 21:23:32,396 DEBUG   SenderThread:7925 [sender.py:send():379] send: files
2024-10-06 21:23:32,396 INFO    SenderThread:7925 [sender.py:_save_file():1454] saving file wandb-metadata.json with policy now
2024-10-06 21:23:32,623 INFO    wandb-upload_0:7925 [upload_job.py:push():130] Uploaded file /var/folders/jv/wvjkll0d0vl_clbchr37hpk40000gn/T/tmph36amf2twandb/pqzqs32v-wandb-metadata.json
2024-10-06 21:23:32,628 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: python_packages
2024-10-06 21:23:32,628 DEBUG   SenderThread:7925 [sender.py:send_request():406] send_request: python_packages
2024-10-06 21:23:32,629 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:23:32,629 DEBUG   SenderThread:7925 [sender.py:send():379] send: telemetry
2024-10-06 21:23:32,629 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: stop_status
2024-10-06 21:23:32,630 DEBUG   SenderThread:7925 [sender.py:send_request():406] send_request: stop_status
2024-10-06 21:23:33,124 INFO    Thread-12 :7925 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212329-b73j8oav/files/conda-environment.yaml
2024-10-06 21:23:33,125 INFO    Thread-12 :7925 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212329-b73j8oav/files/requirements.txt
2024-10-06 21:23:33,125 INFO    Thread-12 :7925 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212329-b73j8oav/files/wandb-metadata.json
2024-10-06 21:23:33,644 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:23:34,130 INFO    Thread-12 :7925 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212329-b73j8oav/files/output.log
2024-10-06 21:23:34,205 ERROR   gpuapple  :7925 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:23:34,665 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:23:35,239 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 21:23:35,645 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:23:36,146 INFO    Thread-12 :7925 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212329-b73j8oav/files/output.log
2024-10-06 21:23:36,218 ERROR   gpuapple  :7925 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:23:36,650 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:23:37,655 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:23:38,226 ERROR   gpuapple  :7925 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:23:38,666 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:23:39,665 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:23:40,237 ERROR   gpuapple  :7925 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:23:40,644 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 21:23:40,670 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:23:41,671 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:23:42,246 ERROR   gpuapple  :7925 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:23:42,676 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:23:43,681 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:23:43,714 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:23:43,715 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:23:43,715 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:23:43,715 DEBUG   SenderThread:7925 [sender.py:send():379] send: history
2024-10-06 21:23:43,715 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:23:43,715 DEBUG   SenderThread:7925 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:23:43,716 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:23:43,717 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:23:43,717 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:23:43,717 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:23:43,717 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:23:43,717 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:23:43,717 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 21:23:43,718 INFO    SenderThread:7925 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:23:43,718 DEBUG   SenderThread:7925 [sender.py:send():379] send: history
2024-10-06 21:23:43,718 DEBUG   SenderThread:7925 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:23:43,719 INFO    SenderThread:7925 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:23:43,719 DEBUG   SenderThread:7925 [sender.py:send():379] send: history
2024-10-06 21:23:43,719 DEBUG   SenderThread:7925 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:23:43,719 INFO    SenderThread:7925 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:23:43,719 DEBUG   SenderThread:7925 [sender.py:send():379] send: history
2024-10-06 21:23:43,719 DEBUG   SenderThread:7925 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:23:43,719 INFO    SenderThread:7925 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:23:43,719 DEBUG   SenderThread:7925 [sender.py:send():379] send: history
2024-10-06 21:23:43,719 DEBUG   SenderThread:7925 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:23:43,719 INFO    SenderThread:7925 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:23:43,719 DEBUG   SenderThread:7925 [sender.py:send():379] send: history
2024-10-06 21:23:43,719 DEBUG   SenderThread:7925 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:23:43,720 INFO    SenderThread:7925 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:23:43,720 DEBUG   SenderThread:7925 [sender.py:send():379] send: history
2024-10-06 21:23:43,720 DEBUG   SenderThread:7925 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:23:43,720 INFO    SenderThread:7925 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:23:43,720 DEBUG   SenderThread:7925 [sender.py:send():379] send: history
2024-10-06 21:23:43,720 DEBUG   SenderThread:7925 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:23:43,720 INFO    SenderThread:7925 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:23:43,720 DEBUG   SenderThread:7925 [sender.py:send():379] send: history
2024-10-06 21:23:43,720 DEBUG   SenderThread:7925 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:23:43,720 INFO    SenderThread:7925 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:23:43,720 DEBUG   SenderThread:7925 [sender.py:send():379] send: history
2024-10-06 21:23:43,720 DEBUG   SenderThread:7925 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:23:43,720 INFO    SenderThread:7925 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:23:43,721 DEBUG   SenderThread:7925 [sender.py:send():379] send: history
2024-10-06 21:23:43,721 DEBUG   SenderThread:7925 [sender.py:send_request():406] send_request: summary_record
2024-10-06 21:23:43,721 INFO    SenderThread:7925 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:23:44,171 INFO    Thread-12 :7925 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212329-b73j8oav/files/wandb-summary.json
2024-10-06 21:23:44,253 ERROR   gpuapple  :7925 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 21:23:44,686 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:23:45,176 INFO    Thread-12 :7925 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212329-b73j8oav/files/output.log
2024-10-06 21:23:45,383 DEBUG   SenderThread:7925 [sender.py:send():379] send: telemetry
2024-10-06 21:23:45,385 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: server_info
2024-10-06 21:23:45,385 DEBUG   SenderThread:7925 [sender.py:send_request():406] send_request: server_info
2024-10-06 21:23:45,420 DEBUG   SenderThread:7925 [sender.py:send():379] send: exit
2024-10-06 21:23:45,420 INFO    SenderThread:7925 [sender.py:send_exit():586] handling exit code: 0
2024-10-06 21:23:45,420 INFO    SenderThread:7925 [sender.py:send_exit():588] handling runtime: 15
2024-10-06 21:23:45,420 INFO    SenderThread:7925 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:23:45,420 INFO    SenderThread:7925 [sender.py:send_exit():594] send defer
2024-10-06 21:23:45,420 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:23:45,420 INFO    HandlerThread:7925 [handler.py:handle_request_defer():184] handle defer: 0
2024-10-06 21:23:45,420 DEBUG   SenderThread:7925 [sender.py:send_request():406] send_request: defer
2024-10-06 21:23:45,420 INFO    SenderThread:7925 [sender.py:send_request_defer():610] handle sender defer: 0
2024-10-06 21:23:45,420 INFO    SenderThread:7925 [sender.py:transition_state():614] send defer: 1
2024-10-06 21:23:45,420 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:23:45,420 INFO    HandlerThread:7925 [handler.py:handle_request_defer():184] handle defer: 1
2024-10-06 21:23:45,421 DEBUG   SenderThread:7925 [sender.py:send_request():406] send_request: defer
2024-10-06 21:23:45,421 INFO    SenderThread:7925 [sender.py:send_request_defer():610] handle sender defer: 1
2024-10-06 21:23:45,421 INFO    SenderThread:7925 [sender.py:transition_state():614] send defer: 2
2024-10-06 21:23:45,421 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:23:45,421 INFO    HandlerThread:7925 [handler.py:handle_request_defer():184] handle defer: 2
2024-10-06 21:23:45,421 INFO    HandlerThread:7925 [system_monitor.py:finish():203] Stopping system monitor
2024-10-06 21:23:45,421 DEBUG   SystemMonitor:7925 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-10-06 21:23:45,421 DEBUG   SystemMonitor:7925 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-10-06 21:23:45,421 DEBUG   SystemMonitor:7925 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-10-06 21:23:45,421 INFO    HandlerThread:7925 [interfaces.py:finish():200] Joined cpu monitor
2024-10-06 21:23:45,421 INFO    HandlerThread:7925 [interfaces.py:finish():200] Joined disk monitor
2024-10-06 21:23:45,421 INFO    HandlerThread:7925 [interfaces.py:finish():200] Joined gpuapple monitor
2024-10-06 21:23:45,421 INFO    HandlerThread:7925 [interfaces.py:finish():200] Joined memory monitor
2024-10-06 21:23:45,421 INFO    HandlerThread:7925 [interfaces.py:finish():200] Joined network monitor
2024-10-06 21:23:45,421 DEBUG   SenderThread:7925 [sender.py:send_request():406] send_request: defer
2024-10-06 21:23:45,421 INFO    SenderThread:7925 [sender.py:send_request_defer():610] handle sender defer: 2
2024-10-06 21:23:45,421 INFO    SenderThread:7925 [sender.py:transition_state():614] send defer: 3
2024-10-06 21:23:45,421 DEBUG   SenderThread:7925 [sender.py:send():379] send: telemetry
2024-10-06 21:23:45,421 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:23:45,421 INFO    HandlerThread:7925 [handler.py:handle_request_defer():184] handle defer: 3
2024-10-06 21:23:45,421 DEBUG   SenderThread:7925 [sender.py:send_request():406] send_request: defer
2024-10-06 21:23:45,421 INFO    SenderThread:7925 [sender.py:send_request_defer():610] handle sender defer: 3
2024-10-06 21:23:45,421 INFO    SenderThread:7925 [sender.py:transition_state():614] send defer: 4
2024-10-06 21:23:45,421 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:23:45,421 INFO    HandlerThread:7925 [handler.py:handle_request_defer():184] handle defer: 4
2024-10-06 21:23:45,421 DEBUG   SenderThread:7925 [sender.py:send_request():406] send_request: defer
2024-10-06 21:23:45,421 INFO    SenderThread:7925 [sender.py:send_request_defer():610] handle sender defer: 4
2024-10-06 21:23:45,422 INFO    SenderThread:7925 [sender.py:transition_state():614] send defer: 5
2024-10-06 21:23:45,422 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:23:45,422 INFO    HandlerThread:7925 [handler.py:handle_request_defer():184] handle defer: 5
2024-10-06 21:23:45,422 DEBUG   SenderThread:7925 [sender.py:send():379] send: summary
2024-10-06 21:23:45,422 INFO    SenderThread:7925 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 21:23:45,422 DEBUG   SenderThread:7925 [sender.py:send_request():406] send_request: defer
2024-10-06 21:23:45,422 INFO    SenderThread:7925 [sender.py:send_request_defer():610] handle sender defer: 5
2024-10-06 21:23:45,422 INFO    SenderThread:7925 [sender.py:transition_state():614] send defer: 6
2024-10-06 21:23:45,422 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:23:45,422 INFO    HandlerThread:7925 [handler.py:handle_request_defer():184] handle defer: 6
2024-10-06 21:23:45,422 DEBUG   SenderThread:7925 [sender.py:send_request():406] send_request: defer
2024-10-06 21:23:45,422 INFO    SenderThread:7925 [sender.py:send_request_defer():610] handle sender defer: 6
2024-10-06 21:23:45,423 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 21:23:45,493 INFO    SenderThread:7925 [sender.py:transition_state():614] send defer: 7
2024-10-06 21:23:45,493 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:23:45,493 INFO    HandlerThread:7925 [handler.py:handle_request_defer():184] handle defer: 7
2024-10-06 21:23:45,493 DEBUG   SenderThread:7925 [sender.py:send_request():406] send_request: defer
2024-10-06 21:23:45,493 INFO    SenderThread:7925 [sender.py:send_request_defer():610] handle sender defer: 7
2024-10-06 21:23:46,182 INFO    Thread-12 :7925 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212329-b73j8oav/files/config.yaml
2024-10-06 21:23:46,183 INFO    Thread-12 :7925 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212329-b73j8oav/files/wandb-summary.json
2024-10-06 21:23:46,183 INFO    Thread-12 :7925 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212329-b73j8oav/files/output.log
2024-10-06 21:23:46,425 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: poll_exit
2024-10-06 21:23:48,192 INFO    Thread-12 :7925 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212329-b73j8oav/files/output.log
2024-10-06 21:23:48,624 INFO    SenderThread:7925 [sender.py:transition_state():614] send defer: 8
2024-10-06 21:23:48,625 DEBUG   SenderThread:7925 [sender.py:send_request():406] send_request: poll_exit
2024-10-06 21:23:48,625 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:23:48,626 INFO    HandlerThread:7925 [handler.py:handle_request_defer():184] handle defer: 8
2024-10-06 21:23:48,626 DEBUG   SenderThread:7925 [sender.py:send_request():406] send_request: defer
2024-10-06 21:23:48,627 INFO    SenderThread:7925 [sender.py:send_request_defer():610] handle sender defer: 8
2024-10-06 21:23:48,627 INFO    SenderThread:7925 [job_builder.py:build():440] Attempting to build job artifact
2024-10-06 21:23:48,628 INFO    SenderThread:7925 [job_builder.py:_get_source_type():580] no source found
2024-10-06 21:23:48,628 INFO    SenderThread:7925 [sender.py:transition_state():614] send defer: 9
2024-10-06 21:23:48,628 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:23:48,628 INFO    HandlerThread:7925 [handler.py:handle_request_defer():184] handle defer: 9
2024-10-06 21:23:48,628 DEBUG   SenderThread:7925 [sender.py:send_request():406] send_request: defer
2024-10-06 21:23:48,629 INFO    SenderThread:7925 [sender.py:send_request_defer():610] handle sender defer: 9
2024-10-06 21:23:48,629 INFO    SenderThread:7925 [dir_watcher.py:finish():358] shutting down directory watcher
2024-10-06 21:23:49,195 INFO    Thread-12 :7925 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212329-b73j8oav/files/output.log
2024-10-06 21:23:49,196 INFO    SenderThread:7925 [dir_watcher.py:finish():388] scan: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212329-b73j8oav/files
2024-10-06 21:23:49,197 INFO    SenderThread:7925 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212329-b73j8oav/files/requirements.txt requirements.txt
2024-10-06 21:23:49,197 INFO    SenderThread:7925 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212329-b73j8oav/files/output.log output.log
2024-10-06 21:23:49,200 INFO    SenderThread:7925 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212329-b73j8oav/files/config.yaml config.yaml
2024-10-06 21:23:49,201 INFO    SenderThread:7925 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212329-b73j8oav/files/wandb-summary.json wandb-summary.json
2024-10-06 21:23:49,203 INFO    SenderThread:7925 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212329-b73j8oav/files/conda-environment.yaml conda-environment.yaml
2024-10-06 21:23:49,206 INFO    SenderThread:7925 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212329-b73j8oav/files/wandb-metadata.json wandb-metadata.json
2024-10-06 21:23:49,206 INFO    SenderThread:7925 [sender.py:transition_state():614] send defer: 10
2024-10-06 21:23:49,208 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:23:49,208 INFO    HandlerThread:7925 [handler.py:handle_request_defer():184] handle defer: 10
2024-10-06 21:23:49,208 DEBUG   SenderThread:7925 [sender.py:send_request():406] send_request: defer
2024-10-06 21:23:49,208 INFO    SenderThread:7925 [sender.py:send_request_defer():610] handle sender defer: 10
2024-10-06 21:23:49,208 INFO    SenderThread:7925 [file_pusher.py:finish():169] shutting down file pusher
2024-10-06 21:23:49,393 INFO    wandb-upload_0:7925 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212329-b73j8oav/files/requirements.txt
2024-10-06 21:23:49,438 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: poll_exit
2024-10-06 21:23:49,439 DEBUG   SenderThread:7925 [sender.py:send_request():406] send_request: poll_exit
2024-10-06 21:23:49,450 INFO    wandb-upload_4:7925 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212329-b73j8oav/files/conda-environment.yaml
2024-10-06 21:23:49,452 INFO    wandb-upload_1:7925 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212329-b73j8oav/files/output.log
2024-10-06 21:23:49,452 INFO    wandb-upload_3:7925 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212329-b73j8oav/files/wandb-summary.json
2024-10-06 21:23:49,453 INFO    wandb-upload_2:7925 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212329-b73j8oav/files/config.yaml
2024-10-06 21:23:49,654 INFO    Thread-11 (_thread_body):7925 [sender.py:transition_state():614] send defer: 11
2024-10-06 21:23:49,655 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:23:49,656 INFO    HandlerThread:7925 [handler.py:handle_request_defer():184] handle defer: 11
2024-10-06 21:23:49,656 DEBUG   SenderThread:7925 [sender.py:send_request():406] send_request: defer
2024-10-06 21:23:49,657 INFO    SenderThread:7925 [sender.py:send_request_defer():610] handle sender defer: 11
2024-10-06 21:23:49,657 INFO    SenderThread:7925 [file_pusher.py:join():175] waiting for file pusher
2024-10-06 21:23:49,659 INFO    SenderThread:7925 [sender.py:transition_state():614] send defer: 12
2024-10-06 21:23:49,659 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:23:49,659 INFO    HandlerThread:7925 [handler.py:handle_request_defer():184] handle defer: 12
2024-10-06 21:23:49,659 DEBUG   SenderThread:7925 [sender.py:send_request():406] send_request: defer
2024-10-06 21:23:49,659 INFO    SenderThread:7925 [sender.py:send_request_defer():610] handle sender defer: 12
2024-10-06 21:23:49,659 INFO    SenderThread:7925 [file_stream.py:finish():601] file stream finish called
2024-10-06 21:23:49,736 INFO    SenderThread:7925 [file_stream.py:finish():605] file stream finish is done
2024-10-06 21:23:49,736 INFO    SenderThread:7925 [sender.py:transition_state():614] send defer: 13
2024-10-06 21:23:49,736 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:23:49,737 INFO    HandlerThread:7925 [handler.py:handle_request_defer():184] handle defer: 13
2024-10-06 21:23:49,737 DEBUG   SenderThread:7925 [sender.py:send_request():406] send_request: defer
2024-10-06 21:23:49,737 INFO    SenderThread:7925 [sender.py:send_request_defer():610] handle sender defer: 13
2024-10-06 21:23:49,737 INFO    SenderThread:7925 [sender.py:transition_state():614] send defer: 14
2024-10-06 21:23:49,738 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: defer
2024-10-06 21:23:49,738 INFO    HandlerThread:7925 [handler.py:handle_request_defer():184] handle defer: 14
2024-10-06 21:23:49,738 DEBUG   SenderThread:7925 [sender.py:send():379] send: final
2024-10-06 21:23:49,738 DEBUG   SenderThread:7925 [sender.py:send():379] send: footer
2024-10-06 21:23:49,739 DEBUG   SenderThread:7925 [sender.py:send_request():406] send_request: defer
2024-10-06 21:23:49,739 INFO    SenderThread:7925 [sender.py:send_request_defer():610] handle sender defer: 14
2024-10-06 21:23:49,740 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: poll_exit
2024-10-06 21:23:49,740 DEBUG   SenderThread:7925 [sender.py:send_request():406] send_request: poll_exit
2024-10-06 21:23:49,741 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 21:23:49,742 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: get_summary
2024-10-06 21:23:49,742 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: sampled_history
2024-10-06 21:23:49,744 DEBUG   HandlerThread:7925 [handler.py:handle_request():158] handle_request: shutdown
2024-10-06 21:23:49,744 INFO    HandlerThread:7925 [handler.py:finish():882] shutting down handler
2024-10-06 21:23:50,743 INFO    SenderThread:7925 [sender.py:finish():1608] shutting down sender
2024-10-06 21:23:50,743 INFO    WriterThread:7925 [datastore.py:close():296] close: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_212329-b73j8oav/run-b73j8oav.wandb
2024-10-06 21:23:50,744 INFO    SenderThread:7925 [file_pusher.py:finish():169] shutting down file pusher
2024-10-06 21:23:50,744 INFO    SenderThread:7925 [file_pusher.py:join():175] waiting for file pusher
